from typing import List, Optional, overload, Unpack, Dict

from . import Rule, Config, CustomLang

class Pos:
    line: int
    column: int
    index: int

class Range:
    start: Pos
    end: Pos

class Edit:
    start_pos: int
    end_pos: int
    inserted_text: str

class SgRoot:
    def __init__(self, src: str, language: str) -> None: ...
    def root(self) -> SgNode: ...
    def filename(self) -> str: ...

class SgNode:
    # Node Inspection
    def range(self) -> Range: ...
    def is_leaf(self) -> bool: ...
    def is_named(self) -> bool: ...
    def is_named_leaf(self) -> bool: ...
    def kind(self) -> str: ...
    def text(self) -> str: ...

    # Refinement
    def matches(self, **rule: Unpack[Rule]) -> bool: ...
    def inside(self, **rule: Unpack[Rule]) -> bool: ...
    def has(self, **rule: Unpack[Rule]) -> bool: ...
    def precedes(self, **rule: Unpack[Rule]) -> bool: ...
    def follows(self, **rule: Unpack[Rule]) -> bool: ...
    def get_match(self, meta_var: str) -> SgNode | None: ...
    def get_multiple_matches(self, meta_var: str) -> list[SgNode]: ...
    def get_transformed(self, meta_var: str) -> str | None: ...
    def __getitem__(self, meta_var: str) -> SgNode: ...

    # Search
    @overload
    def find(self, config: Config) -> SgNode | None: ...
    @overload
    def find(self, **kwargs: Unpack[Rule]) -> SgNode | None: ...
    @overload
    def find_all(self, config: Config) -> list[SgNode]: ...
    @overload
    def find_all(self, **kwargs: Unpack[Rule]) -> list[SgNode]: ...

    # Tree Traversal
    def get_root(self) -> SgRoot: ...
    def field(self, name: str) -> SgNode | None: ...
    def field_children(self, name: str) -> list[SgNode]: ...
    def parent(self) -> SgNode | None: ...
    def child(self, nth: int) -> SgNode | None: ...
    def children(self) -> list[SgNode]: ...
    def ancestors(self) -> list[SgNode]: ...
    def next(self) -> SgNode | None: ...
    def next_all(self) -> list[SgNode]: ...
    def prev(self) -> SgNode | None: ...
    def prev_all(self) -> list[SgNode]: ...

    # Edit
    def replace(self, new_text: str) -> Edit: ...
    def commit_edits(self, edits: list[Edit]) -> str: ...

def register_dynamic_language(langs: dict[str, CustomLang]): ...
