apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gcr-cleaner
  labels:
    app: gcr-cleaner
spec:
  template:
    spec:
      containers:
        - image: us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli
          args:
            - "-repo=gcr.io/acquired-jet-478701-b3/n-autoresearch/Kosmos/BioAgents"
            - "-tag-filter-any=.*"
            - "-keep=5"
          env:
            - name: PORT
              value: "8080"
