# src/shadowtag_v4/services/revenue_engine.py
"""Revenue Engine module

Provides functions to record real‑world revenue events and query the total
revenue generated by the system. This is a lightweight implementation that
stores events in an in‑memory list for the prototype; in production it would
be backed by a persistent database (e.g., PostgreSQL, CloudSQL, etc.).
"""

import threading
import time

# Thread‑safe in‑memory store (replace with DB in prod)
_lock = threading.Lock()
_revenue_events: list[dict] = []
_real_revenue_total: float = 0.0


def record_real_revenue(amount: float, source: str) -> None:
    """Record a real‑dollar revenue event.

    Args:
        amount: Positive amount in USD.
        source: Identifier of the revenue source (e.g., "stripe", "onchain").
    """
    if amount <= 0:
        raise ValueError("Revenue amount must be positive")
    global _real_revenue_total
    with _lock:
        event = {
            "timestamp": time.time(),
            "amount": amount,
            "source": source,
        }
        _revenue_events.append(event)
        _real_revenue_total += amount


def get_total_revenue() -> float:
    """Return the cumulative real revenue recorded so far."""
    with _lock:
        return _real_revenue_total


def list_revenue_events() -> list[dict]:
    """Return a copy of all recorded revenue events."""
    with _lock:
        return list(_revenue_events)
