/**
 * KovelAI Tailwind Theme Extension
 * Auto-generated from DESIGN.md — do not edit manually.
 * Source: apps/kovelai/DESIGN.md
 */

// @ts-check
/** @type {import('tailwindcss').Config['theme']} */
const kovelaiTheme = {
  extend: {
    colors: {
      surface: "#0f0f1a",
      "surface-dim": "#0a0a14",
      "surface-bright": "#1e1e32",
      "surface-container-lowest": "#080812",
      "surface-container-low": "#121220",
      "surface-container": "#161626",
      "surface-container-high": "#1c1c30",
      "surface-container-highest": "#24243c",
      "on-surface": "#e8e8f0",
      "on-surface-variant": "#a3a5b8",
      "inverse-surface": "#e8e8f0",
      "inverse-on-surface": "#1a1a2e",
      outline: "#666680",
      "outline-variant": "#3a3a52",
      "surface-tint": "#8b7bcf",
      primary: "#8b7bcf",
      "on-primary": "#1a1030",
      "primary-container": "#291e44",
      "on-primary-container": "#c4b8e8",
      "inverse-primary": "#53478a",
      secondary: "#a0aed1",
      "on-secondary": "#1a2540",
      "secondary-container": "#2a3a5c",
      "on-secondary-container": "#b8c6e0",
      tertiary: "#e8b4d0",
      "on-tertiary": "#4a1a36",
      "tertiary-container": "#6b3050",
      "on-tertiary-container": "#f0d0e4",
      error: "#ffb4ab",
      "on-error": "#690005",
      "error-container": "#93000a",
      "on-error-container": "#ffdad6",
      "primary-fixed": "#d4c8f4",
      "primary-fixed-dim": "#b0a0dc",
      "on-primary-fixed": "#1a1030",
      "on-primary-fixed-variant": "#57458f",
      "secondary-fixed": "#d0e4ff",
      "secondary-fixed-dim": "#a0aed1",
      "on-secondary-fixed": "#001d35",
      "on-secondary-fixed-variant": "#304b68",
      "tertiary-fixed": "#ffd8e7",
      "tertiary-fixed-dim": "#ffafd3",
      "on-tertiary-fixed": "#3d0026",
      "on-tertiary-fixed-variant": "#85145a",
      background: "#0f0f1a",
      "on-background": "#e8e8f0",
      "surface-variant": "#24243c",
      success: "#69db7c",
      "on-success": "#0a2e14",
      warning: "#ffd43b",
      "on-warning": "#2e2710",
      "accent-glow": "#8b7bcf",
      "accent-cyan": "#22b8f0",
    },
    fontFamily: {
      "display-lg": ["Inter"],
      "display-md": ["Inter"],
      "headline-lg": ["Inter"],
      "headline-md": ["Inter"],
      "body-lg": ["Inter"],
      "body-md": ["Inter"],
      "body-sm": ["Inter"],
      "label-lg": ["Inter"],
      "label-sm": ["Inter"],
      code: ["JetBrains Mono"],
    },
    fontSize: {
      "display-lg": ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "800" }],
      "display-md": ["44px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
      "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      code: ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
    },
    borderRadius: {
      xs: "0.125rem",
      sm: "0.25rem",
      DEFAULT: "0.5rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      pill: "50px",
      full: "9999px",
    },
    spacing: {
      unit: "8px",
      "container-padding": "24px",
      "card-gap": "16px",
      "section-margin": "80px",
      "glass-padding": "24px",
      "nav-height": "72px",
    },
  },
};

module.exports = kovelaiTheme;
