// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START fs_setup_cache_modular]
import { CACHE_SIZE_UNLIMITED, initializeFirestore } from 'firebase/firestore';

const firestoreDb = initializeFirestore(app, {
  cacheSizeBytes: CACHE_SIZE_UNLIMITED,
});
// [END fs_setup_cache_modular]
