#!/bin/bash

################################################################################
# Claude Code Cost Optimization Setup Script
#
# This script automates cost-saving configurations for Claude Code
# Run once: chmod +x setup-cost-optimization.sh && ./setup-cost-optimization.sh
#
# Implements habits from CLAUDE_CODE_COST_OPTIMIZATION.md
################################################################################

set -e  # Exit on error

echo "🚀 Setting up Claude Code cost optimizations..."
echo ""

################################################################################
# 1. Create .clauderc configuration file
################################################################################

echo "📝 Creating .clauderc configuration..."

cat > ~/.clauderc << 'EOF'
# Claude Code Cost Optimization Configuration
# Auto-generated by setup-cost-optimization.sh

# Default model (Habit #1: Use Haiku for 80% of work)
default_model=haiku

# Budget alerts (Habit #7: Turn on budget alerts)
budget_alert_70=true
budget_alert_90=true

# Search result limits (Habit #8: Limit search results)
max_search_results=50
max_grep_results=50

# File read chunk size (Habit #3: Read files in chunks)
default_read_lines=100

# Enable parallel execution by default (Habit #4: Run tasks in parallel)
parallel_execution=true

# Verbose mode for cost tracking
show_cost_estimates=true
EOF

echo "✅ Created ~/.clauderc with optimized defaults"
echo ""

################################################################################
# 2. Create path shortcuts configuration
################################################################################

echo "🔗 Setting up path shortcuts (Habit #10)..."

# Detect project structure and create shortcuts
SHORTCUTS_FILE=".claude-shortcuts"

cat > "$SHORTCUTS_FILE" << 'EOF'
# Claude Code Path Shortcuts
# Usage: Reference these shortcuts instead of full paths
# Example: "read utils" instead of "read /src/lib/utilities/helpers/index.ts"

# Common directories (adjust based on your project structure)
src=/src
lib=/src/lib
utils=/src/lib/utils
components=/src/components
services=/src/services
models=/src/models
config=/src/config
tests=/tests
docs=/docs

# Common files
readme=/README.md
package=/package.json
tsconfig=/tsconfig.json
env=/.env.example
EOF

echo "✅ Created .claude-shortcuts for quick file access"
echo ""

################################################################################
# 3. Create command aliases for common cost-saving patterns
################################################################################

echo "⚡ Creating cost-saving command aliases..."

mkdir -p ~/.claude/aliases

cat > ~/.claude/aliases/cost-optimized << 'EOF'
# Cost-Optimized Command Aliases
# Source this file in your shell: source ~/.claude/aliases/cost-optimized

# Quick model switching
alias claude-haiku='claude --model haiku'
alias claude-sonnet='claude --model sonnet'

# Search shortcuts (Habit #2: Search first, read second)
alias csearch='claude search'
alias cgrep='claude grep --max-results 50'

# Parallel execution (Habit #4)
alias cparallel='claude --parallel'

# Planning shortcuts (Habit #6: Plan major changes first)
alias cplan='claude --model haiku "create a detailed plan for"'

# Exploration (Habit #5: Use explore agent)
alias cexplore='claude explore --thorough quick'

# Todo/checklist creation (Habit #11)
alias ctodo='claude "create a todo list for"'

# Smart reading (Habit #12: Read in chunks)
alias cread-chunk='claude "read lines 1-100 from"'
alias cread-tail='claude "read last 100 lines from"'

# Cost tracking
alias ccost='claude --show-costs'
EOF

echo "✅ Created command aliases in ~/.claude/aliases/cost-optimized"
echo ""

################################################################################
# 4. Create .claudeignore for unnecessary file scanning
################################################################################

echo "🚫 Creating .claudeignore to skip expensive directories..."

cat > .claudeignore << 'EOF'
# Files and directories to skip (saves cost on exploration/search)

# Dependencies
node_modules/
venv/
.venv/
env/
__pycache__/
*.pyc

# Build outputs
dist/
build/
.next/
out/
target/

# Logs (search explicitly when needed)
*.log
logs/

# Large binary files
*.pdf
*.zip
*.tar.gz
*.jpg
*.jpeg
*.png
*.gif
*.mp4
*.mov

# IDE and system files
.idea/
.vscode/
.DS_Store
*.swp
*.swo

# Git
.git/

# Coverage and test outputs
coverage/
.coverage
.nyc_output/
junit.xml
EOF

echo "✅ Created .claudeignore to skip expensive files/directories"
echo ""

################################################################################
# 5. Create cost-tracking helper script
################################################################################

echo "📊 Creating cost tracking helper..."

cat > claude-cost-tracker.sh << 'EOF'
#!/bin/bash
# Cost tracking helper for Claude Code

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "💰 Claude Code Cost Tracker"
echo "=========================="
echo ""

# Check if costs log exists
COSTS_LOG=~/.claude/costs.log

if [ ! -f "$COSTS_LOG" ]; then
    echo "No cost data found. Run Claude Code with --track-costs flag."
    exit 0
fi

# Calculate daily costs
TODAY=$(date +%Y-%m-%d)
TODAY_COST=$(grep "$TODAY" "$COSTS_LOG" | awk '{sum+=$2} END {print sum}')

# Calculate weekly costs
WEEK_AGO=$(date -d '7 days ago' +%Y-%m-%d)
WEEK_COST=$(awk -v date="$WEEK_AGO" '$1 >= date {sum+=$2} END {print sum}' "$COSTS_LOG")

# Calculate monthly costs
MONTH_START=$(date +%Y-%m-01)
MONTH_COST=$(awk -v date="$MONTH_START" '$1 >= date {sum+=$2} END {print sum}' "$COSTS_LOG")

# Budget thresholds (customize these)
DAILY_BUDGET=2.14   # ~$15/week = ~$2.14/day
WEEKLY_BUDGET=15.00
MONTHLY_BUDGET=65.00

echo "Today:     \$$TODAY_COST / \$$DAILY_BUDGET budget"
echo "This Week: \$$WEEK_COST / \$$WEEKLY_BUDGET budget"
echo "This Month: \$$MONTH_COST / \$$MONTHLY_BUDGET budget"
echo ""

# Warnings
DAILY_PCT=$(echo "scale=2; $TODAY_COST / $DAILY_BUDGET * 100" | bc)
WEEKLY_PCT=$(echo "scale=2; $WEEK_COST / $WEEKLY_BUDGET * 100" | bc)
MONTHLY_PCT=$(echo "scale=2; $MONTH_COST / $MONTHLY_BUDGET * 100" | bc)

if (( $(echo "$MONTHLY_PCT > 90" | bc -l) )); then
    echo -e "${RED}⚠️  WARNING: 90%+ of monthly budget used!${NC}"
elif (( $(echo "$MONTHLY_PCT > 70" | bc -l) )); then
    echo -e "${YELLOW}⚠️  NOTICE: 70%+ of monthly budget used${NC}"
else
    echo -e "${GREEN}✅ Budget looking good${NC}"
fi

echo ""
echo "Top cost-saving tips:"
echo "  1. Use haiku for routine tasks (5x cheaper)"
echo "  2. Search before reading large files (100x cheaper)"
echo "  3. Read files in chunks, not all at once"
echo "  4. Create a plan before major refactoring"
echo ""
EOF

chmod +x claude-cost-tracker.sh

echo "✅ Created cost tracking script: ./claude-cost-tracker.sh"
echo ""

################################################################################
# 6. Create quick reference cheat sheet
################################################################################

echo "📋 Creating quick reference cheat sheet..."

cat > CLAUDE_COST_CHEATSHEET.md << 'EOF'
# Claude Code Cost Optimization Cheat Sheet

Print this and keep it visible while coding!

## Before Every Task

- [ ] Can I use **Haiku** instead of Sonnet?
- [ ] Can I **search** instead of read?
- [ ] Can I read a **chunk** instead of whole file?
- [ ] Can I run these in **parallel**?
- [ ] Should I **plan first**?

## Cost-Saving Commands

| Instead of... | Use... | Savings |
|---------------|--------|---------|
| `read large.log` | `search for ERROR in large.log` | **100x** |
| `read database.ts` | `read lines 1-100 from database.ts` | **100x** |
| Read 3 files sequentially | `run in parallel: read a, b, c` | **3x faster** |
| Random searching | `explore codebase for X` | **5x cheaper** |
| Refactor immediately | `create a plan for X` first | **100x** |
| `find all matches` | `find first 50 matches` | **10x** |

## Quick Commands

```bash
# Use Haiku (5x cheaper)
claude --model haiku

# Search before reading
"search for ERROR in file.log"

# Read in chunks
"read lines 100-200 from file.ts"

# Parallel execution
"run in parallel: task1, task2, task3"

# Explore unfamiliar code
"explore this codebase for authentication"

# Plan major changes
"create a plan for refactoring X"

# Limit results
"find first 50 matches for TODO"

# Be specific
"fix login bug in auth.ts:45"

# Use shortcuts
"read utils" # instead of full path

# Create checklist
"create a todo list for X"

# Filter first
"show only ERROR from logs"

# Use session memory
"use the errors we found earlier"
```

## Model Selection Guide

### Use Haiku (5x cheaper) for:
- Bug fixes
- File reads
- Simple edits
- Code formatting
- Basic refactoring
- Routine tasks

### Use Sonnet for:
- Complex architecture
- Multi-file refactoring
- Advanced debugging
- System design
- Learning new codebases

## Red Flags (Expensive Patterns)

🚨 "read entire file" → Search first or read in chunks
🚨 "help me fix this" → Be specific with file:line
🚨 Sequential tasks → Run in parallel
🚨 No plan → Plan major changes first
🚨 "find all" → Limit to first 50 results

## Budget Alerts

- ✅ **Under 70%**: On track
- ⚠️  **70-90%**: Watch spending
- 🚨 **Over 90%**: Review practices

Run `./claude-cost-tracker.sh` daily!

---

**Goal:** From $400/week → $15/week
**Result:** $18,480/year saved 🎉
EOF

echo "✅ Created CLAUDE_COST_CHEATSHEET.md"
echo ""

################################################################################
# 7. Update .gitignore
################################################################################

echo "📝 Updating .gitignore..."

if [ -f .gitignore ]; then
    # Add Claude-specific ignores if not already present
    if ! grep -q "\.claude" .gitignore; then
        cat >> .gitignore << 'EOF'

# Claude Code files
.claude/
.clauderc
.claude-shortcuts
EOF
        echo "✅ Updated .gitignore"
    else
        echo "ℹ️  .gitignore already configured"
    fi
else
    echo "⚠️  No .gitignore found, skipping"
fi

echo ""

################################################################################
# 8. Create project-specific path shortcuts
################################################################################

echo "🔍 Detecting project structure for shortcuts..."

# Auto-detect common directories and create shortcuts
SHORTCUTS=""

if [ -d "src" ]; then
    SHORTCUTS="${SHORTCUTS}src=./src\n"

    # Check subdirectories
    [ -d "src/services" ] && SHORTCUTS="${SHORTCUTS}services=./src/services\n"
    [ -d "src/models" ] && SHORTCUTS="${SHORTCUTS}models=./src/models\n"
    [ -d "src/controllers" ] && SHORTCUTS="${SHORTCUTS}controllers=./src/controllers\n"
    [ -d "src/routes" ] && SHORTCUTS="${SHORTCUTS}routes=./src/routes\n"
    [ -d "src/utils" ] && SHORTCUTS="${SHORTCUTS}utils=./src/utils\n"
    [ -d "src/lib" ] && SHORTCUTS="${SHORTCUTS}lib=./src/lib\n"
    [ -d "src/components" ] && SHORTCUTS="${SHORTCUTS}components=./src/components\n"
fi

[ -d "tests" ] && SHORTCUTS="${SHORTCUTS}tests=./tests\n"
[ -d "test" ] && SHORTCUTS="${SHORTCUTS}test=./test\n"
[ -d "docs" ] && SHORTCUTS="${SHORTCUTS}docs=./docs\n"
[ -d "config" ] && SHORTCUTS="${SHORTCUTS}config=./config\n"

if [ ! -z "$SHORTCUTS" ]; then
    echo -e "$SHORTCUTS" >> .claude-shortcuts
    echo "✅ Added project-specific shortcuts"
else
    echo "ℹ️  No common directories detected"
fi

echo ""

################################################################################
# 9. Create prompt templates directory (Habit #16)
################################################################################

echo "📝 Creating prompt templates for cost-efficient prompting..."

mkdir -p .claude-prompts

# Bug fix template (Haiku)
cat > .claude-prompts/bug-fix-haiku.md << 'EOF'
# Bug Fix Template (Use with Haiku - 5x cheaper)

Fix [ERROR_TYPE] in [FILE]:[LINE]

Error: [EXACT_ERROR_MESSAGE]

Expected behavior: [WHAT_SHOULD_HAPPEN]
Actual behavior: [WHAT_HAPPENS]

Context:
- [KEY_VARIABLE_1]: [VALUE]
- [KEY_VARIABLE_2]: [VALUE]

Return: Code fix with 1-line explanation

---
Example:
Fix TypeError in auth.ts:234 - user.token is undefined
Add null check before accessing user.token
EOF

# Refactoring plan template (Haiku → Sonnet)
cat > .claude-prompts/refactor-plan.md << 'EOF'
# Refactoring Plan Template (Two-stage: Haiku → Sonnet)

## Stage 1: Create Plan (Haiku)

Create a plan to [GOAL] in these files:
- [FILE_1]: [ROLE]
- [FILE_2]: [ROLE]
- [FILE_3]: [ROLE]

Constraints:
- [CONSTRAINT_1]
- [CONSTRAINT_2]

Output: 5-step plan with risk assessment

## Stage 2: Implement (Sonnet, after reviewing plan)

Implement step [N] of the plan above.
[PASTE_PLAN_STEP]

Files to modify:
- [FILE_1]
- [FILE_2]

Output: Complete code changes

---
Savings: 50% vs direct Sonnet refactoring
EOF

# System analysis template (Gemini)
cat > .claude-prompts/system-analysis-gemini.md << 'EOF'
# System Analysis Template (Use with Gemini for documentation/compliance)

Analyze [SYSTEM_NAME] based on [DOCS/SPECS].

Focus areas:
1. [AREA_1]: [SPECIFIC_METRICS]
2. [AREA_2]: [SPECIFIC_METRICS]
3. [AREA_3]: [SPECIFIC_METRICS]

Output format:
## [AREA_1]
- Metric: [VALUE]
- Assessment: [GOOD/CONCERN]
- Recommendation: [ACTION]

## [AREA_2]
...

Target confidence: [60/70/90]%
Flag assumptions clearly.

---
Example: Gemini Ingestion Layer analysis
Savings: 87% vs generic analysis (1 round vs 7)
EOF

# Code search template (Haiku)
cat > .claude-prompts/code-search-haiku.md << 'EOF'
# Code Search Template (Haiku)

Search [DIRECTORY] for [PATTERN]

Criteria:
- [CRITERION_1]
- [CRITERION_2]

Limit: First 50 results
Sort by: [RELEVANCE/DATE/FILE]

Output: File:line for each match

---
Cost: $0.05 (vs $0.50 for unlimited search)
EOF

# Multi-source data analysis template (Gemini)
cat > .claude-prompts/multi-source-analysis.md << 'EOF'
# Multi-Source Data Analysis Template (Gemini)

Analyze data quality across sources:

Sources:
- [SOURCE_1]: [DESCRIPTION]
- [SOURCE_2]: [DESCRIPTION]
- [SOURCE_3]: [DESCRIPTION]

Metrics per source:
- Volume: Items/day
- Quality: [QUALITY_METRIC]
- Cost: $/item
- Timeliness: Lag from event to ingestion

Identify:
1. Coverage gaps
2. Cost outliers
3. Quality issues
4. Optimization opportunities

Output: Table + 3 top recommendations

---
Use case: Gemini Ingestion Layer coverage analysis
EOF

# README for templates
cat > .claude-prompts/README.md << 'EOF'
# Claude Code Prompt Templates

Cost-optimized prompt templates for common tasks (Habit #16).

## Usage

1. Copy the appropriate template
2. Fill in the [PLACEHOLDERS]
3. Use with the specified model (Haiku/Sonnet/Gemini)
4. Track your cost savings!

## Templates

- **bug-fix-haiku.md** - Bug fixes on Haiku (80% savings vs Sonnet)
- **refactor-plan.md** - Two-stage refactoring (50% savings)
- **system-analysis-gemini.md** - System/compliance analysis (87% savings)
- **code-search-haiku.md** - Efficient code search (90% savings)
- **multi-source-analysis.md** - Data quality analysis

## Cost Impact

Using these templates can save 50-90% compared to generic prompts.

See [PROMPT_ENGINEERING_COST_OPTIMIZATION.md](../PROMPT_ENGINEERING_COST_OPTIMIZATION.md)
for detailed case studies and advanced techniques.

## Customization

Feel free to:
- Add your own templates for repetitive tasks
- Adjust placeholders to match your workflow
- Share templates with your team
EOF

echo "✅ Created prompt templates in .claude-prompts/"
echo ""

################################################################################
# Summary
################################################################################

echo "════════════════════════════════════════════════════════════════"
echo "✅ Cost optimization setup complete!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "What was configured:"
echo "  ✅ ~/.clauderc with optimized defaults (Haiku, search limits)"
echo "  ✅ .claude-shortcuts for quick file access"
echo "  ✅ Command aliases in ~/.claude/aliases/cost-optimized"
echo "  ✅ .claudeignore to skip expensive files"
echo "  ✅ Cost tracking script: ./claude-cost-tracker.sh"
echo "  ✅ Quick reference: CLAUDE_COST_CHEATSHEET.md"
echo "  ✅ Prompt templates: .claude-prompts/ (Habit #16)"
echo ""
echo "Next steps:"
echo "  1. Read CLAUDE_CODE_COST_OPTIMIZATION.md (full guide with 16 habits)"
echo "  2. Check out PROMPT_ENGINEERING_COST_OPTIMIZATION.md (advanced techniques)"
echo "  3. Print CLAUDE_COST_CHEATSHEET.md (keep it visible)"
echo "  4. Browse .claude-prompts/ for reusable templates"
echo "  5. Run ./claude-cost-tracker.sh daily to monitor costs"
echo "  6. Practice these habits in your next 5 tasks"
echo ""
echo "Expected savings: $400/week → $15/week = $18,480/year 🎉"
echo ""
echo "Questions? Check the documentation files created in this directory."
echo "════════════════════════════════════════════════════════════════"
