#!/usr/bin/env python3
"""
Post verified PR findings to GitHub using gh CLI
Part of Jules + GCA Sovereign PR Review System
"""

import argparse
import json
import subprocess
import sys
from typing import Dict, List


def post_findings(pr_number: int, findings: List[Dict]):
    """Post verified findings as inline comments"""

    if not findings:
        print("✅ No verified findings to post.")
        # Post positive confirmation
        cmd = [
            "gh",
            "pr",
            "review",
            str(pr_number),
            "--comment",
            "-b",
            "✅ Antigravity Swarm: No issues found after behavioral verification.",
        ]
        subprocess.run(cmd)
        return

    for finding in findings:
        severity = finding.get("severity_emoji", "🔴")
        comment = finding.get("comment", "Issue detected")
        line = finding.get("line", 1)

        body = f"{severity} {comment}\n\n**Verified via:** {finding.get('source', 'Three-Tier Architecture')}"

        cmd = [
            "gh",
            "pr",
            "review",
            str(pr_number),
            "--comment",
            "-b",
            body,
        ]

        try:
            subprocess.run(cmd, check=True, capture_output=True)
            print(f"✅ Posted: {severity} on line {line}")
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to post finding: {e}")


def load_findings_from_file(filepath: str) -> List[Dict]:
    """Load findings from JSON file (generated by run_swarm.py)"""
    try:
        with open(filepath) as f:
            return json.load(f)
    except FileNotFoundError:
        return []


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--pr", type=int, required=True)
    parser.add_argument("--findings-file", type=str, default="pr_findings.json")
    args = parser.parse_args()

    findings = load_findings_from_file(args.findings_file)
    post_findings(args.pr, findings)
