#!/usr/bin/env python3
# Copyright (c) 2026 ShadowTag, Inc. All rights reserved.

"""Post verified PR findings to GitHub using GitHub App installation token.

Part of Jules + GCA Sovereign PR Review System.
Uses GitHub App JWT (not gh CLI) per github_doctrine.
"""

from __future__ import annotations

import argparse
import json
import ssl
import urllib.request
from pathlib import Path


def post_findings(pr_number: int, findings: list[dict], token: str) -> None:
  """Post verified findings as PR review comments."""
  ctx = ssl.create_default_context()
  base_url = f"https://api.github.com/repos/ShadowTag-v2/Monorepo-Uphillsnowball/pulls/{pr_number}/reviews"

  if not findings:
    print("✅ No verified findings to post.")
    # Post positive confirmation
    review_data = json.dumps(
      {
        "body": "✅ **Antigravity Swarm**: No issues found after behavioral verification.\n\n"
        "- Rule Engine: Clean\n"
        "- Hardware Verification: N/A\n"
        "- Doctrine Compliance: Passed",
        "event": "COMMENT",
      }
    ).encode()

    req = urllib.request.Request(
      base_url,
      data=review_data,
      method="POST",
      headers={
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json",
      },
    )
    try:
      urllib.request.urlopen(req, context=ctx)
      print("✅ Posted clean review comment")
    except urllib.error.HTTPError as e:
      print(f"❌ Failed to post review: {e.code}")
    return

  # Build review body from findings
  body_lines = [
    f"## 🔍 Antigravity Swarm Review — {len(findings)} findings\n",
  ]

  for i, finding in enumerate(findings, 1):
    severity = finding.get("severity_emoji", "🔴")
    comment = finding.get("comment", "Issue detected")
    source = finding.get("source", "Three-Tier Architecture")
    body_lines.append(f"{i}. {severity} {comment}\n   **Source:** {source}\n")

  review_data = json.dumps(
    {
      "body": "\n".join(body_lines),
      "event": "COMMENT",
    }
  ).encode()

  req = urllib.request.Request(
    base_url,
    data=review_data,
    method="POST",
    headers={
      "Authorization": f"token {token}",
      "Accept": "application/vnd.github+json",
      "Content-Type": "application/json",
    },
  )
  try:
    urllib.request.urlopen(req, context=ctx)
    print(f"✅ Posted review with {len(findings)} findings")
  except urllib.error.HTTPError as e:
    print(f"❌ Failed to post review: {e.code} — {e.read().decode()[:200]}")


def load_findings_from_file(filepath: str) -> list[dict]:
  """Load findings from JSON file (generated by run_swarm.py)."""
  try:
    return json.loads(Path(filepath).read_text())
  except (FileNotFoundError, json.JSONDecodeError):
    return []


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description="Post PR findings to GitHub")
  parser.add_argument("--pr", type=int, required=True, help="PR number")
  parser.add_argument("--findings-file", type=str, default="pr_findings.json")
  args = parser.parse_args()

  # Load token
  token_path = Path("/tmp/gh_app_token.txt")
  if token_path.exists():
    token = token_path.read_text().strip()
  else:
    import sys

    print("❌ No GitHub App token found at /tmp/gh_app_token.txt")
    print("   Run: python3 scripts/auth_github_app.py --export")
    sys.exit(1)

  findings = load_findings_from_file(args.findings_file)
  post_findings(args.pr, findings, token)
