/**
 * V25 Jules Ascension — Dart Edge Compiler Bridge
 *
 * Integrates dart-mcp-server task/doc/comment patterns for tracking
 * deployment state, issue management, and fleet service lifecycle.
 * Maps Cloud Run fleet operations to Dart's structured task system.
 *
 * References:
 *   - external_repos/dart-mcp-server/index.ts (Dart MCP patterns)
 *   - external_repos/dart-mcp-server/tools.ts (tool definitions)
 *   - src/orchestration/jules_fleet_orchestrator.ts (fleet state)
 *
 * @module orchestration/dart_edge_bridge
 * Copyright (c) 2026 ShadowTag, Inc. All rights reserved.
 */

import type {
  FleetService,
  DeploymentResult,
  FleetHealthReport,
} from './jules_fleet_orchestrator.js';

// ============================================================================
// TYPES
// ============================================================================

export interface DartTask {
  id: string;
  title: string;
  description: string;
  status: DartTaskStatus;
  priority: DartPriority;
  assignee: string | null;
  labels: string[];
  createdAt: string;
  updatedAt: string;
  metadata: Record<string, unknown>;
}

export type DartTaskStatus =
  | 'Backlog'
  | 'In Progress'
  | 'In Review'
  | 'Done'
  | 'Blocked'
  | 'Cancelled';

export type DartPriority = 'Critical' | 'High' | 'Medium' | 'Low' | 'None';

export interface DartDoc {
  id: string;
  title: string;
  text: string;
  folder: string;
  createdAt: string;
  updatedAt: string;
}

export interface DartComment {
  id: string;
  taskId: string;
  text: string;
  createdAt: string;
}

export interface DartMcpPlan {
  type: 'dart_mcp_plan';
  operations: DartOperation[];
}

export interface DartOperation {
  tool: string;
  args: Record<string, unknown>;
  description: string;
}

// ============================================================================
// PRIORITY MAPPING
// ============================================================================

const PRIORITY_MAP: Record<string, DartPriority> = {
  P0: 'Critical',
  P1: 'High',
  P2: 'Medium',
};

const STATUS_FROM_SERVICE: Record<string, DartTaskStatus> = {
  HEALTHY: 'Done',
  DEGRADED: 'In Review',
  DEPLOYING: 'In Progress',
  FAILED: 'Blocked',
  UNKNOWN: 'Backlog',
};

// ============================================================================
// DART EDGE BRIDGE
// ============================================================================

/**
 * DartEdgeBridge — Maps fleet operations to Dart task management.
 *
 * Creates structured task tracking for every deployment, health check,
 * and incident. Produces MCP execution plans for the dart-mcp-server.
 *
 * CRITICAL: This produces PLANS, not side effects.
 */
export class DartEdgeBridge {
  private readonly dartboardId: string;
  private readonly taskRegistry: Map<string, DartTask> = new Map();

  constructor(dartboardId: string = 'fleet-ops') {
    this.dartboardId = dartboardId;
  }

  // --------------------------------------------------------------------------
  // TASK CREATION FROM FLEET EVENTS
  // --------------------------------------------------------------------------

  /**
   * Plan Dart task creation for a fleet deployment.
   */
  planDeploymentTask(
    serviceName: string,
    prompt: string,
    priority: string = 'P1',
  ): DartMcpPlan {
    const dartPriority = PRIORITY_MAP[priority] ?? 'Medium';

    return {
      type: 'dart_mcp_plan',
      operations: [
        {
          tool: 'create_task',
          args: {
            title: `[Deploy] ${serviceName}`,
            description: `Fleet deployment for Cloud Run service.\n\n## Prompt\n${prompt}\n\n## Service\n- Name: ${serviceName}\n- Priority: ${priority}\n- Generated by: V25 Jules Ascension`,
            status: 'In Progress',
            priority: dartPriority,
            labels: ['fleet-deploy', 'v25-ascension', serviceName],
          },
          description: `Create deployment tracking task for ${serviceName}`,
        },
      ],
    };
  }

  /**
   * Plan Dart task update from deployment result.
   */
  planDeploymentResultUpdate(result: DeploymentResult): DartMcpPlan {
    const status: DartTaskStatus = result.state === 'completed' ? 'Done' : 'Blocked';
    const operations: DartOperation[] = [];

    // Update task status
    operations.push({
      tool: 'update_task',
      args: {
        title: `[Deploy] ${result.serviceName}`,
        status,
        description: `Deployment ${result.state}.\n\nSession: ${result.sessionId}\nDuration: ${result.durationMs}ms\nPR: ${result.pullRequestUrl ?? 'N/A'}`,
      },
      description: `Update deployment task for ${result.serviceName} → ${status}`,
    });

    // Add comment with activity log
    if (result.activities.length > 0) {
      const activityLog = result.activities
        .map((a) => `- [${a.type}] ${a.title ?? a.message ?? ''}`)
        .join('\n');

      operations.push({
        tool: 'add_task_comment',
        args: {
          text: `## Activity Log\n\n${activityLog}\n\n---\n*Auto-generated by V25 Jules Ascension*`,
        },
        description: `Add activity log comment for ${result.serviceName}`,
      });
    }

    return { type: 'dart_mcp_plan', operations };
  }

  // --------------------------------------------------------------------------
  // FLEET HEALTH → DART SYNC
  // --------------------------------------------------------------------------

  /**
   * Plan Dart tasks from fleet health report.
   *
   * Creates or updates tasks for degraded/failed services.
   * Closes tasks for healthy services that were previously tracked.
   */
  planHealthSync(report: FleetHealthReport): DartMcpPlan {
    const operations: DartOperation[] = [];

    for (const service of report.services) {
      const dartStatus = STATUS_FROM_SERVICE[service.status] ?? 'Backlog';
      const existingTask = this.taskRegistry.get(service.name);

      if (service.status === 'FAILED' || service.status === 'DEGRADED') {
        if (!existingTask) {
          // Create incident task
          operations.push({
            tool: 'create_task',
            args: {
              title: `[Incident] ${service.name} — ${service.status}`,
              description: `Fleet service health degradation detected.\n\n## Service\n- Name: ${service.name}\n- Status: ${service.status}\n- Region: ${service.region}\n- Health: ${service.healthEndpoint}\n- Last Deploy: ${service.lastDeployedAt ?? 'Never'}`,
              status: dartStatus,
              priority: service.status === 'FAILED' ? 'Critical' : 'High',
              labels: ['fleet-incident', service.name, service.status.toLowerCase()],
            },
            description: `Create incident task for ${service.name}`,
          });
        } else {
          // Update existing task
          operations.push({
            tool: 'update_task',
            args: {
              title: `[Incident] ${service.name} — ${service.status}`,
              status: dartStatus,
            },
            description: `Update incident status for ${service.name}`,
          });
        }
      } else if (service.status === 'HEALTHY' && existingTask) {
        // Close resolved incident
        operations.push({
          tool: 'update_task',
          args: {
            title: `[Incident] ${service.name} — RESOLVED`,
            status: 'Done' as DartTaskStatus,
          },
          description: `Resolve incident for ${service.name}`,
        });
      }
    }

    // Create health report doc
    operations.push({
      tool: 'create_doc',
      args: {
        title: `Fleet Health Report — ${report.timestamp}`,
        text: this.formatHealthDoc(report),
        folder: 'fleet-reports',
      },
      description: `Create fleet health report document`,
    });

    return { type: 'dart_mcp_plan', operations };
  }

  // --------------------------------------------------------------------------
  // SERVICE → TASK MAPPING
  // --------------------------------------------------------------------------

  /**
   * Sync fleet service state to internal task registry.
   */
  syncServiceState(services: FleetService[]): void {
    for (const service of services) {
      const task: DartTask = {
        id: `svc_${service.name}`,
        title: `[Service] ${service.name}`,
        description: `Cloud Run service: ${service.name}`,
        status: STATUS_FROM_SERVICE[service.status] ?? 'Backlog',
        priority: 'Medium',
        assignee: null,
        labels: ['fleet-service', service.name],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        metadata: {
          region: service.region,
          imageUrl: service.imageUrl,
          healthEndpoint: service.healthEndpoint,
          sessionId: service.sessionId,
        },
      };
      this.taskRegistry.set(service.name, task);
    }
  }

  // --------------------------------------------------------------------------
  // DOCUMENT GENERATION
  // --------------------------------------------------------------------------

  /**
   * Format a fleet health report as a Dart document.
   */
  private formatHealthDoc(report: FleetHealthReport): string {
    const lines: string[] = [
      `# Fleet Health Report`,
      ``,
      `**Generated**: ${report.timestamp}`,
      `**Total Services**: ${report.totalServices}`,
      ``,
      `## Summary`,
      `| Status | Count |`,
      `|--------|-------|`,
      `| ✅ Healthy | ${report.healthy} |`,
      `| ⚠️ Degraded | ${report.degraded} |`,
      `| ❌ Failed | ${report.failed} |`,
      `| 🔄 Deploying | ${report.deploying} |`,
      ``,
      `## Services`,
    ];

    for (const s of report.services) {
      const icon =
        s.status === 'HEALTHY' ? '✅' :
        s.status === 'DEGRADED' ? '⚠️' :
        s.status === 'FAILED' ? '❌' :
        s.status === 'DEPLOYING' ? '🔄' : '❓';

      lines.push(`- ${icon} **${s.name}** (${s.region}) — ${s.status}`);
    }

    lines.push('', '---', '*Auto-generated by V25 Jules Ascension Fleet Orchestrator*');
    return lines.join('\n');
  }

  // --------------------------------------------------------------------------
  // DIAGNOSTICS
  // --------------------------------------------------------------------------

  getDiagnostics(): Record<string, unknown> {
    return {
      bridge: 'dart_edge_bridge_v25',
      dartboardId: this.dartboardId,
      trackedTasks: this.taskRegistry.size,
      tasksByStatus: this.getTaskStatusCounts(),
    };
  }

  private getTaskStatusCounts(): Record<string, number> {
    const counts: Record<string, number> = {};
    for (const task of this.taskRegistry.values()) {
      counts[task.status] = (counts[task.status] ?? 0) + 1;
    }
    return counts;
  }
}
