"""Chat API endpoints with streaming support."""

import structlog
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.db.database import get_db
from app.schemas.chat import (
    ChatRequest,
    ChatResponse,
    ConversationCreate,
    ConversationResponse,
    MessageResponse,
)
from app.services.ai_assistant import AIAssistant

logger = structlog.get_logger()
router = APIRouter(prefix="/chat", tags=["chat"])


async def get_ai_assistant(
    db: AsyncSession = Depends(get_db),
    provider: str = settings.DEFAULT_LLM_PROVIDER,
) -> AIAssistant:
    """Dependency for getting AI assistant instance."""
    return AIAssistant(db=db, provider=provider)


@router.post("/completions", response_model=ChatResponse)
async def chat_completion(request: ChatRequest, db: AsyncSession = Depends(get_db)):
    """Send a chat message and get a completion response.

    Supports:
    - New and existing conversations
    - Custom system prompts
    - Multiple LLM providers (Anthropic, OpenAI)
    - Conversation history management
    """
    try:
        assistant = AIAssistant(db=db, provider=request.model_provider, model=request.model_name)

        if request.stream:
            # For streaming requests, redirect to streaming endpoint
            raise HTTPException(
                status_code=400,
                detail="Use /chat/stream endpoint for streaming responses",
            )

        response, session_id = await assistant.chat(
            message=request.message,
            session_id=request.session_id,
            system_prompt=request.system_prompt,
            temperature=request.temperature,
            max_tokens=request.max_tokens,
            save_history=request.save_history,
        )

        return ChatResponse(
            session_id=session_id,
            message=response,
            role="assistant",
            model=request.model_name or assistant.model,
            provider=request.model_provider or assistant.provider,
        )

    except ValueError as e:
        logger.error("Chat completion failed - validation error", error=str(e))
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error("Chat completion failed", error=str(e))
        raise HTTPException(status_code=500, detail="Internal server error")


@router.post("/stream")
async def chat_stream(request: ChatRequest, db: AsyncSession = Depends(get_db)):
    """Send a chat message and stream the completion response.

    Streams the response in real-time as it's generated by the LLM.
    """
    try:
        assistant = AIAssistant(db=db, provider=request.model_provider, model=request.model_name)

        async def generate():
            """Generate streaming response."""
            try:
                session_id = None
                async for chunk, sid in assistant.chat_stream(
                    message=request.message,
                    session_id=request.session_id,
                    system_prompt=request.system_prompt,
                    temperature=request.temperature,
                    max_tokens=request.max_tokens,
                    save_history=request.save_history,
                ):
                    session_id = sid
                    # Send chunk with session ID in first chunk
                    if session_id and chunk:
                        yield chunk

            except Exception as e:
                logger.error("Streaming error", error=str(e))
                yield f"\n\nError: {e!s}"

        return StreamingResponse(generate(), media_type="text/event-stream")

    except ValueError as e:
        logger.error("Chat stream failed - validation error", error=str(e))
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error("Chat stream failed", error=str(e))
        raise HTTPException(status_code=500, detail="Internal server error")


@router.post("/conversations", response_model=ConversationResponse)
async def create_conversation(
    request: ConversationCreate,
    assistant: AIAssistant = Depends(get_ai_assistant),
):
    """Create a new conversation.

    Use this to start a new chat session with custom settings.
    """
    try:
        conversation = await assistant.create_conversation(
            user_id=request.user_id,
            title=request.title,
            system_prompt=request.system_prompt,
            metadata=request.metadata,
        )

        return ConversationResponse.model_validate(conversation)

    except Exception as e:
        logger.error("Conversation creation failed", error=str(e))
        raise HTTPException(status_code=500, detail="Internal server error")


@router.get("/conversations/{session_id}", response_model=ConversationResponse)
async def get_conversation(session_id: str, assistant: AIAssistant = Depends(get_ai_assistant)):
    """Get a conversation by session ID.

    Includes all messages in the conversation.
    """
    try:
        conversation = await assistant.get_conversation(session_id)

        if not conversation:
            raise HTTPException(status_code=404, detail=f"Conversation not found: {session_id}")

        return ConversationResponse.model_validate(conversation)

    except HTTPException:
        raise
    except Exception as e:
        logger.error("Get conversation failed", error=str(e))
        raise HTTPException(status_code=500, detail="Internal server error")


@router.get("/conversations/{session_id}/messages", response_model=list[MessageResponse])
async def get_conversation_messages(
    session_id: str,
    limit: int = 100,
    assistant: AIAssistant = Depends(get_ai_assistant),
):
    """Get messages from a conversation.

    Returns conversation history with optional limit.
    """
    try:
        messages = await assistant.get_conversation_history(session_id=session_id, limit=limit)

        return [MessageResponse.model_validate(msg) for msg in messages]

    except Exception as e:
        logger.error("Get messages failed", error=str(e))
        raise HTTPException(status_code=500, detail="Internal server error")


@router.delete("/conversations/{session_id}")
async def delete_conversation(session_id: str, assistant: AIAssistant = Depends(get_ai_assistant)):
    """Delete a conversation and all its messages."""
    try:
        deleted = await assistant.delete_conversation(session_id)

        if not deleted:
            raise HTTPException(status_code=404, detail=f"Conversation not found: {session_id}")

        return {"message": "Conversation deleted successfully", "session_id": session_id}

    except HTTPException:
        raise
    except Exception as e:
        logger.error("Delete conversation failed", error=str(e))
        raise HTTPException(status_code=500, detail="Internal server error")


@router.get("/conversations", response_model=list[ConversationResponse])
async def list_conversations(
    user_id: str = None,
    limit: int = 50,
    offset: int = 0,
    assistant: AIAssistant = Depends(get_ai_assistant),
):
    """List conversations, optionally filtered by user ID."""
    try:
        conversations = await assistant.list_conversations(
            user_id=user_id,
            limit=limit,
            offset=offset,
        )

        return [ConversationResponse.model_validate(conv) for conv in conversations]

    except Exception as e:
        logger.error("List conversations failed", error=str(e))
        raise HTTPException(status_code=500, detail="Internal server error")
