#!/usr/bin/env python3
"""
BugBot PR Hook: Wires BugBot into GitHub PR events
Integrates with Dual-Model CI pipeline

Part of 4-Module Agent Stack
Cost: $0 (pure static analysis)
"""

import json
import os
import subprocess
import sys
from pathlib import Path

# Add parent dir for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.bugbot import BugBot


def get_changed_files(diff_range: str = "origin/main...HEAD") -> list:
    """Get list of changed Python files."""
    try:
        result = subprocess.run(
            ["git", "diff", diff_range, "--name-only"], capture_output=True, text=True, check=True
        )
        files = [f.strip() for f in result.stdout.strip().split("\n") if f.strip()]
        return [f for f in files if f.endswith(".py")]
    except subprocess.CalledProcessError as e:
        print(f"Warning: Git diff failed: {e}", file=sys.stderr)
        return []


def build_github_comment(results: dict, changed_files: list) -> str:
    """Build GitHub-flavored markdown comment."""
    health = results.get("health_score", 0)
    total = results.get("total_issues", 0)
    rec = results.get("recommendation", "UNKNOWN")

    # Header with health badge
    if health >= 90:
        badge = "🟢"
        status = "Excellent"
    elif health >= 70:
        badge = "🟡"
        status = "Good"
    elif health >= 50:
        badge = "🟠"
        status = "Needs Improvement"
    else:
        badge = "🔴"
        status = "Critical Issues"

    comment = f"""## {badge} BugBot Analysis

| Metric | Value |
|--------|-------|
| Health Score | **{health}/100** ({status}) |
| Total Issues | {total} |
| Files Analyzed | {len(changed_files)} |
| Recommendation | **{rec}** |

"""

    details = results.get("details", {})

    # Security issues (most important)
    security = details.get("security", {})
    if security.get("issues", 0) > 0:
        sev = security.get("severity", {})
        comment += f"""### 🔒 Security Issues
- High: {sev.get("high", 0)}
- Medium: {sev.get("medium", 0)}
- Low: {sev.get("low", 0)}

"""

    # Pylint issues
    pylint = details.get("pylint", {})
    if pylint.get("issues", 0) > 0:
        comment += f"### 📝 Code Quality (Pylint): {pylint['issues']} issues\n\n"

    # Type issues
    mypy = details.get("mypy", {})
    if mypy.get("issues", 0) > 0:
        comment += f"### 🔷 Type Issues (MyPy): {mypy['issues']} issues\n\n"

    # Complexity
    complexity = details.get("complexity", {})
    if complexity.get("high_complexity_functions", 0) > 0:
        comment += (
            f"### 🔄 Complexity Issues: {complexity['high_complexity_functions']} functions\n\n"
        )

    comment += """---
<sub>🤖 Generated by BugBot (Dual-Model CI Pipeline)</sub>
"""

    return comment


def post_github_comment(comment: str, pr_number: str = None):
    """Post comment to GitHub PR using gh CLI."""
    if not pr_number:
        pr_number = os.environ.get("PR_NUMBER") or os.environ.get("GITHUB_REF", "").split("/")[-2]

    if not pr_number or pr_number == "merge":
        print("No PR number found, outputting to stdout")
        print(comment)
        return

    try:
        subprocess.run(["gh", "pr", "comment", pr_number, "--body", comment], check=True)
        print(f"Posted comment to PR #{pr_number}")
    except subprocess.CalledProcessError as e:
        print(f"Failed to post comment: {e}", file=sys.stderr)
        print(comment)


def main(diff_range: str = "origin/main...HEAD", target: str = None):
    """Run BugBot analysis and post results."""

    # Get changed files
    changed_files = get_changed_files(diff_range)

    if not changed_files:
        print("✅ No Python files changed")
        return

    # Determine target directory
    if target is None:
        # Find common parent of changed files
        if all(f.startswith("src/") for f in changed_files):
            target = "src/"
        elif all(f.startswith("agents/") for f in changed_files):
            target = "agents/"
        else:
            target = "./"

    print(f"///▞ BUGBOT :: Analyzing {len(changed_files)} changed files in {target}")

    # Run BugBot
    bot = BugBot()
    results = bot.full_scan(target)

    # Build and post comment
    comment = build_github_comment(results, changed_files)

    # Write results for CI artifacts
    with open("bugbot_results.json", "w") as f:
        json.dump(results, f, indent=2)

    with open("bugbot_comment.md", "w") as f:
        f.write(comment)

    # Post to GitHub if in CI
    if os.environ.get("GITHUB_ACTIONS"):
        post_github_comment(comment)
    else:
        print("\n" + comment)

    # Exit code based on recommendation
    if results.get("recommendation") == "PASS":
        print("✅ BugBot PASSED")
        sys.exit(0)
    else:
        print("⚠️  BugBot recommends review")
        # Don't fail CI, just warn
        sys.exit(0)


if __name__ == "__main__":
    diff_range = sys.argv[1] if len(sys.argv) > 1 else "origin/main...HEAD"
    target = sys.argv[2] if len(sys.argv) > 2 else None
    main(diff_range, target)
