#!/bin/bash
# Transcript Saver - Auto-commit session logs to GitHub
# Usage: ./scripts/save_transcript.sh "Session description"

set -e

TRANSCRIPT_DIR="transcripts"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DESCRIPTION="${1:-Claude Code Session}"
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

echo "///▞ TRANSCRIPT SAVER :: Starting"

# Create transcripts directory if needed
mkdir -p "$REPO_ROOT/$TRANSCRIPT_DIR"

# Create session file
SESSION_FILE="$REPO_ROOT/$TRANSCRIPT_DIR/session_${TIMESTAMP}.md"

cat > "$SESSION_FILE" << EOF
# Session Transcript: $DESCRIPTION
**Date:** $(date +%Y-%m-%d\ %H:%M:%S)
**Branch:** $(git branch --show-current 2>/dev/null || echo "unknown")

## Summary
$DESCRIPTION

## Files Modified
$(git diff --name-only HEAD 2>/dev/null || echo "No git changes detected")

## Git Status
\`\`\`
$(git status --short 2>/dev/null || echo "Not a git repository")
\`\`\`

---
*Generated by ShadowTagAi Transcript Saver*
EOF

echo "///▞ TRANSCRIPT SAVER :: Created $SESSION_FILE"

# Commit to git if in a repo
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    git add "$SESSION_FILE"
    git commit -m "transcript: $DESCRIPTION

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"

    echo "///▞ TRANSCRIPT SAVER :: Committed to git"

    # Push if remote exists
    if git remote get-url origin > /dev/null 2>&1; then
        git push origin $(git branch --show-current) 2>/dev/null && \
            echo "///▞ TRANSCRIPT SAVER :: Pushed to remote" || \
            echo "///▞ TRANSCRIPT SAVER :: Push failed (check branch protection)"
    fi
else
    echo "///▞ TRANSCRIPT SAVER :: Not in git repo, file saved locally only"
fi

echo "///▞ TRANSCRIPT SAVER :: Complete"
