import os
import signal
import subprocess
import sys
import time

from google import genai
from google.cloud import storage
from google.genai import types


class CinematicStudio:
    """
    ⏺ ///▙▖▙▖▞ THE STUDIO (Cursor-Killer)
    Record -> Upload -> Multimodal Critique via gemini-3.1-flash-lite-preview
    """

    def __init__(self, display=":99", project_id=None):
        self.display = display
        self.pid_file = "/tmp/ffmpeg.pid"
        self.out_file = "/tmp/demo_video.mp4"
        self.project_id = project_id or os.getenv("GCP_PROJECT_ID", "shadowtag-omega-v4")

    def action(self):
        if os.path.exists(self.out_file):
            os.remove(self.out_file)

        if sys.platform == "darwin":
            # macOS native AVFoundation capture (Screen 1)
            print("🍎 [Studio] macOS detected. Using AVFoundation capture.")
            cmd = [
                "ffmpeg",
                "-y",
                "-f",
                "avfoundation",
                "-i",
                "1:none",
                "-c:v",
                "libx264",
                "-preset",
                "ultrafast",
                "-pix_fmt",
                "yuv420p",
                "-r",
                "30",
                self.out_file,
            ]
        else:
            # Linux Xvfb capture
            print(f"🐧 [Studio] Linux detected. Using X11grab on {self.display}.")
            cmd = [
                "ffmpeg",
                "-y",
                "-video_size",
                "1920x1080",
                "-framerate",
                "30",
                "-f",
                "x11grab",
                "-i",
                f"{self.display}.0",
                "-c:v",
                "libx264",
                "-preset",
                "ultrafast",
                "-pix_fmt",
                "yuv420p",
                self.out_file,
            ]

        proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        with open(self.pid_file, "w") as f:
            f.write(str(proc.pid))
        print("🎥 [Studio] Action! Hardware Camera rolling.")

    def cut_and_upload(self):
        try:
            with open(self.pid_file) as f:
                pid = int(f.read().strip())
            os.kill(pid, signal.SIGINT)  # Graceful SIGINT finalizes the MP4 'moov' atom
        except Exception:
            print("⚠️ [Studio] No active FFmpeg PID found.")
            pass

        time.sleep(3)

        print("☁️ [Studio] Cut! Uploading artifact to GCP Vault...")
        client = storage.Client(project=self.project_id)
        bucket_name = f"shadowtag-artifacts-{self.project_id}"

        try:
            bucket = client.get_bucket(bucket_name)
        except Exception:
            bucket = client.create_bucket(bucket_name, location="us-central1")

        blob = bucket.blob(f"agent_demos/demo_{int(time.time())}.mp4")
        blob.upload_from_filename(self.out_file, content_type="video/mp4")
        blob.make_public()  # Public-read for GitHub PR embedding

        print(f"🔗 Artifact Secured: {blob.public_url}")
        return blob.public_url, f"gs://{bucket_name}/{blob.name}"

    def critique(self, gs_uri, intent):
        print("👁️ [Studio] The Critic (Gemini 3.1 Flash Lite Preview) is reviewing the tape...")
        client = genai.Client(vertexai=True, project=self.project_id, location="us-central1")

        try:
            video_part = types.Part.from_uri(file_uri=gs_uri, mime_type="video/mp4")

            prompt = f"""
            You are the Lead QA Engineer. Watch this automated UI test video generated by the Triad swarm.
            The agent's intent was: "{intent}".
            1. Did the UI load correctly?
            2. Did the agent successfully execute the requested feature?
            3. Are there any visual glitches, overlaps, infinite spinners, or broken CSS?
            Reply strictly with 'PASS' if flawless, or 'FAIL: [Reason]'.
            """
            response = client.models.generate_content(
                model="gemini-3.1-flash-lite-preview", contents=[video_part, prompt]
            )
            verdict = response.text.strip()
            print(f"⚖️ [Critic] Verdict: {verdict}")
            return verdict
        except Exception as e:
            print(f"❌ [Critic] Internal Review Error: {e}")
            return f"FAIL: {str(e)}"


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(1)
    action = sys.argv[1]
    studio = CinematicStudio()

    if action == "start":
        studio.action()
    elif action == "stop_and_critique":
        intent = sys.argv[2] if len(sys.argv) > 2 else "Verify visual functionality"
        pub_url, gs_uri = studio.cut_and_upload()
        verdict = studio.critique(gs_uri, intent)

        with open("/tmp/vid_url.txt", "w") as f:
            f.write(pub_url)
        with open("/tmp/vid_verdict.txt", "w") as f:
            f.write(verdict)
