// This snippet file was generated by processing the source file:
// ./auth-next/custom-dependencies.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

import { initializeApp } from 'firebase/app';
// [START auth_sign_in_redirect_manual_deps_modular]
import {
  browserLocalPersistence,
  browserPopupRedirectResolver,
  GoogleAuthProvider,
  indexedDBLocalPersistence,
  initializeAuth,
  signInWithRedirect,
} from 'firebase/auth';

const app = initializeApp({
  /** Your app config */
});
const auth = initializeAuth(app, {
  persistence: [indexedDBLocalPersistence, browserLocalPersistence],
});

// Later
signInWithRedirect(auth, new GoogleAuthProvider(), browserPopupRedirectResolver);
// [END auth_sign_in_redirect_manual_deps_modular]
