// This snippet file was generated by processing the source file:
// ./auth-next/custom-dependencies.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

import { initializeApp } from 'firebase/app';
// [START auth_only_browser_local_modular]
import { browserLocalPersistence, initializeAuth } from 'firebase/auth';

const app = initializeApp({
  /** Your app config */
});
const auth = initializeAuth(app, {
  persistence: browserLocalPersistence,
  // No popupRedirectResolver defined
});
// [END auth_only_browser_local_modular]
