/**
 * @file    ai_denoise_model.cpp
 * @brief   Embedded FDnCNN model data (isolated translation unit)
 * @author  AllenK (Kwyshell)
 * @license MIT
 *
 * @details
 * This file exists solely to #include the model_core.mem.h header,
 * which contains the NCNN model weights as C arrays (~6.8 MB of text).
 *
 * By isolating it in its own .cpp, we avoid recompiling other files
 * when only model data changes, and prevent the heavy header from
 * slowing down incremental builds.
 *
 * The generated arrays are `static`, so we expose them via accessor
 * functions that ai_denoise.cpp can call.
 *
 * Generated by: ncnn2mem model_core_fp16.param model_core_fp16.bin
 * Model: FDnCNN Color, FP16, ~1.3 MB weights
 */

#ifdef GWT_HAS_AI_DENOISE

// These headers define static const unsigned char arrays:
//   model_core_fp16_param_bin[]  - network topology (binary param)
//   model_core_fp16_bin[]        - FP16 weights
#include "model_core.id.h"
#include "model_core.mem.h"

namespace gwt::ai_model {

const unsigned char* param_data() {
    return S__CodeForge_tools_gemini_watermark_tool_release_repo_external_ncnn_model_convert_output_model_core_fp16_param_bin;
}

const unsigned char* bin_data() {
    return S__CodeForge_tools_gemini_watermark_tool_release_repo_external_ncnn_model_convert_output_model_core_fp16_bin;
}

} // namespace gwt::ai_model

#endif // GWT_HAS_AI_DENOISE
