"""XML Tag Registry — standardized agent message framing tags.

Ported from Claude Code v2.1.91 constants/xml.ts.
Defines the complete XML tag vocabulary used for inter-agent communication,
terminal I/O framing, task notifications, and cross-session messaging.
"""

from packages.xml_tags.tags import (
    BASH_INPUT_TAG,
    BASH_STDERR_TAG,
    BASH_STDOUT_TAG,
    CHANNEL_MESSAGE_TAG,
    CHANNEL_TAG,
    COMMAND_ARGS_TAG,
    COMMAND_MESSAGE_TAG,
    COMMAND_NAME_TAG,
    COMMON_HELP_ARGS,
    COMMON_INFO_ARGS,
    CROSS_SESSION_MESSAGE_TAG,
    FORK_BOILERPLATE_TAG,
    FORK_DIRECTIVE_PREFIX,
    LOCAL_COMMAND_CAVEAT_TAG,
    LOCAL_COMMAND_STDERR_TAG,
    LOCAL_COMMAND_STDOUT_TAG,
    OUTPUT_FILE_TAG,
    REASON_TAG,
    REMOTE_REVIEW_PROGRESS_TAG,
    REMOTE_REVIEW_TAG,
    STATUS_TAG,
    SUMMARY_TAG,
    TASK_ID_TAG,
    TASK_NOTIFICATION_TAG,
    TASK_TYPE_TAG,
    TEAMMATE_MESSAGE_TAG,
    TERMINAL_OUTPUT_TAGS,
    TICK_TAG,
    TOOL_USE_ID_TAG,
    ULTRAPLAN_TAG,
    WORKTREE_BRANCH_TAG,
    WORKTREE_PATH_TAG,
    WORKTREE_TAG,
    is_terminal_output_tag,
    unwrap_xml_tag,
    wrap_xml_tag,
)

__all__ = [
    "BASH_INPUT_TAG",
    "BASH_STDERR_TAG",
    "BASH_STDOUT_TAG",
    "CHANNEL_MESSAGE_TAG",
    "CHANNEL_TAG",
    "COMMAND_ARGS_TAG",
    "COMMAND_MESSAGE_TAG",
    "COMMAND_NAME_TAG",
    "COMMON_HELP_ARGS",
    "COMMON_INFO_ARGS",
    "CROSS_SESSION_MESSAGE_TAG",
    "FORK_BOILERPLATE_TAG",
    "FORK_DIRECTIVE_PREFIX",
    "LOCAL_COMMAND_CAVEAT_TAG",
    "LOCAL_COMMAND_STDERR_TAG",
    "LOCAL_COMMAND_STDOUT_TAG",
    "OUTPUT_FILE_TAG",
    "REASON_TAG",
    "REMOTE_REVIEW_PROGRESS_TAG",
    "REMOTE_REVIEW_TAG",
    "STATUS_TAG",
    "SUMMARY_TAG",
    "TASK_ID_TAG",
    "TASK_NOTIFICATION_TAG",
    "TASK_TYPE_TAG",
    "TEAMMATE_MESSAGE_TAG",
    "TERMINAL_OUTPUT_TAGS",
    "TICK_TAG",
    "TOOL_USE_ID_TAG",
    "ULTRAPLAN_TAG",
    "WORKTREE_BRANCH_TAG",
    "WORKTREE_PATH_TAG",
    "WORKTREE_TAG",
    "is_terminal_output_tag",
    "unwrap_xml_tag",
    "wrap_xml_tag",
]
