#!/usr/bin/env python3
"""
UI Consistency Auditor — 10X Vibe Edition
Detects inconsistent buttons, orphaned actions, duplicate components, broken flows
in React/TSX/JSX files. Adapted for shadowtagai-monorepo-v2 (focus on apps/, libs/, packages/)
"""

import re
from pathlib import Path
from collections import defaultdict
from typing import Dict, List

ISSUES: Dict[str, List[str]] = defaultdict(list)

EXCLUDE_DIRS = {
  ".git",
  "node_modules",
  "dist",
  "build",
  ".next",
  ".venv",
  "__pycache__",
}


def is_excluded(path: Path) -> bool:
  return any(part in EXCLUDE_DIRS for part in path.parts)


def audit_file(file_path: Path):
  if file_path.suffix.lower() not in {".tsx", ".jsx", ".ts", ".js"}:
    return
  if is_excluded(file_path):
    return

  try:
    content = file_path.read_text(encoding="utf-8", errors="ignore")
    rel_path = str(file_path.relative_to(Path(".")))

    # 1. Empty onClick handlers
    if re.search(r"onClick=\{\s*\}", content):
      ISSUES["empty_onClick"].append(rel_path)

    # 2. Placeholder href="#"
    if re.search(r'href=["\']#["\']', content):
      ISSUES["placeholder_href"].append(rel_path)

    # 3. Inline style on buttons (Tailwind/MUI inconsistency)
    if re.search(r"<button[^>]*style=\{\{[^}]+\}\}", content, re.IGNORECASE):
      ISSUES["inline_style_button"].append(rel_path)

    # 4. Too many buttons in one file (monolithic component smell)
    button_count = len(re.findall(r"<(button|Button)\b", content, re.IGNORECASE))
    if button_count > 6:
      ISSUES["too_many_buttons"].append(f"{rel_path} ({button_count} buttons)")

    # 5. Orphaned <a> without href or with javascript:void
    if re.search(
      r'<a\s+(?!.*href)[^>]*>|<a[^>]*href=["\']javascript:void\(0\)',
      content,
      re.IGNORECASE,
    ):
      ISSUES["orphaned_link"].append(rel_path)

    # 6. Duplicate component patterns (simple heuristic)
    if re.search(r"const\s+\w+Button\s*=\s*\(", content) and button_count > 3:
      ISSUES["possible_duplicate_button_component"].append(rel_path)

    # 7. Missing aria-label on interactive elements (a11y)
    interactive_without_aria = re.findall(
      r"<(button|input|select|textarea)[^>]*>(?![^<]*aria-label)",
      content,
      re.IGNORECASE,
    )
    if len(interactive_without_aria) > 2:
      ISSUES["missing_aria_label"].append(
        f"{rel_path} ({len(interactive_without_aria)} elements)"
      )

  except Exception as e:
    print(f"⚠️  Error auditing {file_path}: {e}")


def main():
  print("# 🖥️  10X Vibe UI Consistency Audit Report\n")
  print("**Focus:** apps/, libs/, packages/, tools/\n")

  # Primary UI surface
  for base in ["apps", "libs", "packages", "tools"]:
    base_path = Path(base)
    if base_path.exists():
      for file_path in base_path.rglob("*"):
        if file_path.is_file():
          audit_file(file_path)

  # Also check root-level components if any
  for file_path in Path(".").glob("*.{tsx,jsx,ts,js}"):
    if file_path.is_file():
      audit_file(file_path)

  total_issues = sum(len(v) for v in ISSUES.values())
  print(f"**Total issues found:** {total_issues}\n")

  if not ISSUES:
    print("✅ **No UI inconsistencies detected.** Excellent work!")
    return

  for issue_type, files in sorted(ISSUES.items()):
    emoji = "🔴" if "empty" in issue_type or "placeholder" in issue_type else "🟡"
    print(f"## {emoji} {issue_type.replace('_', ' ').title()}")
    for f in files:
      print(f"- `{f}`")
    print()

  print("\n**Recommended fixes:**")
  print("- Replace `onClick={}` with proper handlers or remove")
  print("- Use `href` with real routes or `onClick` instead of `#`")
  print("- Prefer Tailwind/MUI classes over inline styles")
  print("- Split large components (>6 buttons) into sub-components")
  print("- Add `aria-label` for accessibility compliance\n")

  print(
    "*Generated by 10X Vibe UI Auditor — run locally with `python tools/scripts/ui_consistency_auditor.py`*"
  )


if __name__ == "__main__":
  main()
