// oxlint-disable triple-slash-reference
/// <reference path="modules/ast-grep.d.ts" />

export type {
  ChildKinds,
  CompleteRuleConfig,
  DefinitionKind,
  DefinitionOptions,
  DefinitionResult,
  Edit,
  ExtractField,
  FieldNames,
  FieldNode,
  FileOption,
  FileReferences,
  FindConfig,
  GetSelector,
  GetSelectorOptions,
  Kinds,
  NamedChildKinds,
  NamedKinds,
  NodeBasicInfo,
  NodeFieldInfo,
  NodeMethod,
  NodeType,
  NthChild,
  NthChildObject,
  PatternObject,
  PatternStyle,
  Position,
  Range,
  RefineNode,
  Relation,
  RootKind,
  Rule,
  RuleConfig,
  Severity,
  SgNode,
  SgRoot,
  Strictness,
  Transform,
  TransformOptions,
  TypesInField,
  TypesMap,
} from "codemod:ast-grep";

export { jssgTransform, parse, parseAsync } from "codemod:ast-grep";
