apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: us-central1-docker.pkg.dev/serverless-runtimes/google-22/run/universal:public-image-next
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 9b9fb075-45ff-4b2c-9b1e-815dd0223bc9
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/shadowtag-omega-v2/cloud-run-source-deploy/jetski-bridge
    run.googleapis.com/build-name: projects/509993604693/locations/us-central1/builds/9b9fb075-45ff-4b2c-9b1e-815dd0223bc9
    run.googleapis.com/build-source-location: gs://run-sources-shadowtag-omega-v2-us-central1/services/jetski-bridge/1768720536.218328-fec7935f025e4a2bbc2e5da2ed611e4c.zip#1768720561915422
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/urls: '["https://jetski-bridge-509993604693.us-central1.run.app","https://jetski-bridge-s2its66sea-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: jetski-bridge
  namespace: '509993604693'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 552.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: utkkdvfhkx
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/shadowtag-omega-v2/cloud-run-source-deploy/jetski-bridge@sha256:18a2cf7aec7bfa8cbbf714c86305d6e39ac9d135fa25492fd836b4c3a97c24e7
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: redacted@shadowtag-v4.local
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
