/**
 * Type definitions bridged from @google/jules-sdk v0.2.0
 *
 * These are the subset of Jules SDK types that the ShadowTag orchestration
 * layer depends on. When the SDK is available as an npm dependency, these
 * will be replaced with direct imports from '@google/jules-sdk'.
 *
 * API: https://jules.googleapis.com/v1alpha/sessions
 */

/** Configuration for creating a new Jules session */
export interface SessionConfig {
  /** The prompt to send to Jules */
  prompt: string;
  /** Source context for the repository */
  sourceContext?: SourceContext;
  /** Whether plan approval is required before execution */
  requirePlanApproval?: boolean;
  /** Automation mode for the session */
  automationMode?: "AUTO_CREATE_PR" | "MANUAL" | "AUTO_MERGE";
}

/** Source context pointing to a GitHub repository */
export interface SourceContext {
  /** Source identifier, e.g. "sources/github/ShadowTag-v2/Monorepo-Uphillsnowball" */
  source: string;
  /** GitHub-specific repo context */
  githubRepoContext?: {
    startingBranch?: string;
  };
}

/** Possible states of a Jules session */
export type SessionState =
  | "PENDING"
  | "RUNNING"
  | "PLAN_REVIEW"
  | "COMPLETED"
  | "FAILED"
  | "CANCELLED";

/** Output from a completed session */
export interface SessionOutput {
  /** Unique session identifier */
  sessionId: string;
  /** Current state */
  state: SessionState;
  /** Artifacts produced */
  artifacts?: Artifact[];
  /** Pull request created (if automationMode was AUTO_CREATE_PR) */
  pullRequest?: PullRequest;
  /** Plan generated */
  plan?: Plan;
}

/** An artifact produced by Jules */
export interface Artifact {
  /** Artifact type identifier */
  type: string;
  /** Artifact content */
  content: string;
  /** MIME type */
  mimeType?: string;
}

/** A changeset of file modifications */
export interface ChangeSet {
  /** Files modified */
  files: Array<{
    path: string;
    action: "create" | "modify" | "delete";
    content?: string;
    patch?: string;
  }>;
}

/** A plan generated by Jules */
export interface Plan {
  /** Plan steps */
  steps: PlanStep[];
  /** Overall plan description */
  description?: string;
}

/** A single step in a plan */
export interface PlanStep {
  /** Step description */
  description: string;
  /** Whether this step has been completed */
  completed?: boolean;
}

/** A pull request created by Jules */
export interface PullRequest {
  /** PR URL */
  url: string;
  /** PR number */
  number: number;
  /** PR title */
  title: string;
  /** PR body */
  body?: string;
}

/** An activity event from a Jules session */
export interface Activity {
  /** Activity type */
  type: string;
  /** Timestamp */
  timestamp: string;
  /** Activity data */
  data?: Record<string, unknown>;
}

/** Summary of session activities */
export interface ActivitySummary {
  /** Total activities */
  total: number;
  /** Activities by type */
  byType: Record<string, number>;
}
