#!/usr/bin/env python3
"""Agent0 POC: Self-Evolving Framework for ATP 5-19 Rule Synthesis

Based on arXiv:2511.16043v1 - Symbiotic dual-agent co-evolution:
- Curriculum Agent: Generates increasingly difficult violation scenarios
- Executor Agent: Creates detection rules (ATP_519_scan patterns)
- Zero external training data: Self-evolving via mutual pressure

Routes through minions (600 agents) for execution.

Part of PNKLN governance stack.
"""

import asyncio
import json
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any

import requests


class RiskCategory(Enum):
    """ATP 5-19 Risk Categories (Probability)."""

    A = "frequent"  # Likely to occur often
    B = "likely"  # Probably will occur
    C = "occasional"  # Might occur
    D = "seldom"  # Unlikely but possible
    E = "unlikely"  # Improbable but not impossible


class Severity(Enum):
    """ATP 5-19 Severity Categories."""

    I = "catastrophic"  # Death or system loss
    II = "critical"  # Severe injury/damage
    III = "marginal"  # Minor injury/damage
    IV = "negligible"  # Less than minor


@dataclass
class ViolationScenario:
    """ATP 5-19 violation scenario generated by curriculum agent."""

    scenario_id: str
    description: str
    risk_category: RiskCategory
    severity: Severity
    difficulty: int  # 1-10
    expected_brake: str
    domain: str = "general"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class DetectionRule:
    """ATP_519_scan detection rule generated by executor agent."""

    rule_id: str
    pattern: str
    action: str  # BLOCK, WARN, LOG
    confidence: float  # 0.0-1.0
    scenario_id: str
    reasoning: str = ""
    false_positive_rate: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class EvolutionState:
    """State of the co-evolution loop."""

    iteration: int = 0
    difficulty: int = 1
    rules_generated: list[DetectionRule] = field(default_factory=list)
    scenarios_generated: list[ViolationScenario] = field(default_factory=list)
    success_streak: int = 0
    failure_streak: int = 0
    total_cost: float = 0.0


class Agent0POC:
    """Agent0 Proof of Concept for ATP 5-19 rule synthesis.

    Implements self-evolving dual-agent architecture:
    - Curriculum Agent: Proposes violation scenarios at current difficulty
    - Executor Agent: Generates detection rules for scenarios
    - Difficulty adjusts based on executor success rate

    Routes through minions for LLM execution.
    """

    # Risk level matrix from ATP 5-19
    RISK_MATRIX = {
        (RiskCategory.A, Severity.I): "EH",  # Extremely High
        (RiskCategory.A, Severity.II): "EH",
        (RiskCategory.A, Severity.III): "H",  # High
        (RiskCategory.A, Severity.IV): "M",  # Medium
        (RiskCategory.B, Severity.I): "EH",
        (RiskCategory.B, Severity.II): "H",
        (RiskCategory.B, Severity.III): "M",
        (RiskCategory.B, Severity.IV): "L",  # Low
        (RiskCategory.C, Severity.I): "H",
        (RiskCategory.C, Severity.II): "M",
        (RiskCategory.C, Severity.III): "M",
        (RiskCategory.C, Severity.IV): "L",
        (RiskCategory.D, Severity.I): "M",
        (RiskCategory.D, Severity.II): "M",
        (RiskCategory.D, Severity.III): "L",
        (RiskCategory.D, Severity.IV): "L",
        (RiskCategory.E, Severity.I): "M",
        (RiskCategory.E, Severity.II): "L",
        (RiskCategory.E, Severity.III): "L",
        (RiskCategory.E, Severity.IV): "L",
    }

    def __init__(
        self,
        minions_url: str = "http://localhost:8600",
        max_iterations: int = 100,
        confidence_threshold: float = 0.8,
    ):
        """Initialize Agent0 POC.

        Args:
            minions_url: minions server URL
            max_iterations: Maximum evolution iterations
            confidence_threshold: Minimum confidence for rule acceptance

        """
        self.fm_url = minions_url
        self.max_iterations = max_iterations
        self.confidence_threshold = confidence_threshold
        self.state = EvolutionState()

        # Stats tracking
        self.stats = {
            "start_time": datetime.now(),
            "curriculum_calls": 0,
            "executor_calls": 0,
            "rules_accepted": 0,
            "rules_rejected": 0,
            "difficulty_increases": 0,
            "difficulty_decreases": 0,
        }

        print("///▞ AGENT0 :: Initialized")
        print(f"///▞ AGENT0 :: minions: {minions_url}")
        print(f"///▞ AGENT0 :: Max iterations: {max_iterations}")

    def _call_minions(self, prompt: str, endpoint: str = "task") -> dict[str, Any]:
        """Call minions API."""
        try:
            response = requests.post(
                f"{self.fm_url}/{endpoint}",
                json={"prompt": prompt},
                timeout=60,
            )
            response.raise_for_status()
            return response.json()
        except Exception as e:
            return {"error": str(e), "response": ""}

    async def curriculum_agent(self, difficulty: int, domain: str = "general") -> ViolationScenario:
        """Curriculum Agent: Generate violation scenario at given difficulty.

        Higher difficulty = more nuanced edge cases, ambiguous situations,
        multi-factor violations, or cross-domain scenarios.
        """
        self.stats["curriculum_calls"] += 1

        prompt = f"""You are a curriculum agent generating ATP 5-19 risk violation scenarios.

Generate a violation scenario at DIFFICULTY LEVEL {difficulty}/10.

Difficulty guide:
- 1-3: Simple, clear violations (single factor, obvious risk)
- 4-6: Moderate complexity (multiple factors, subtle risks)
- 7-9: Complex scenarios (edge cases, ambiguous situations)
- 10: Expert-level (cross-domain, cascading failures, adversarial)

Domain: {domain}

Output ONLY valid JSON:
{{
  "description": "detailed violation scenario description",
  "risk_category": "A|B|C|D|E",
  "severity": "I|II|III|IV",
  "expected_brake": "Purpose → Reason → Brake chain",
  "edge_factors": ["factor1", "factor2"],
  "ambiguity_points": ["what makes this tricky"]
}}

Be creative but realistic. Make difficulty {difficulty} scenarios appropriately challenging."""

        result = self._call_minions(prompt, "governance")

        try:
            # Parse response
            response_text = result.get("response", "{}")
            if isinstance(response_text, str):
                # Extract JSON from response
                if "```json" in response_text:
                    response_text = response_text.split("```json")[1].split("```")[0]
                elif "```" in response_text:
                    response_text = response_text.split("```")[1].split("```")[0]

                data = json.loads(response_text)
            else:
                data = response_text

            scenario = ViolationScenario(
                scenario_id=f"scn_{datetime.now().timestamp():.0f}_{difficulty}",
                description=data.get("description", "Unknown scenario"),
                risk_category=RiskCategory[data.get("risk_category", "C")],
                severity=Severity[data.get("severity", "III")],
                difficulty=difficulty,
                expected_brake=data.get("expected_brake", ""),
                domain=domain,
                metadata={
                    "edge_factors": data.get("edge_factors", []),
                    "ambiguity_points": data.get("ambiguity_points", []),
                },
            )
            self.state.scenarios_generated.append(scenario)
            return scenario

        except (json.JSONDecodeError, KeyError):
            # Return fallback scenario
            return ViolationScenario(
                scenario_id=f"scn_fallback_{difficulty}",
                description="Fallback: General risk scenario",
                risk_category=RiskCategory.C,
                severity=Severity.III,
                difficulty=difficulty,
                expected_brake="Evaluate → Assess → Mitigate",
                domain=domain,
            )

    async def executor_agent(self, scenario: ViolationScenario) -> DetectionRule:
        """Executor Agent: Generate detection rule for violation scenario.

        Creates ATP_519_scan pattern that can identify the violation.
        """
        self.stats["executor_calls"] += 1

        risk_level = self.RISK_MATRIX.get((scenario.risk_category, scenario.severity), "M")

        prompt = f"""You are an executor agent creating ATP_519_scan detection rules.

Generate a detection rule for this violation scenario:

SCENARIO:
{scenario.description}

Risk Category: {scenario.risk_category.value} ({scenario.risk_category.name})
Severity: {scenario.severity.value} ({scenario.severity.name})
Risk Level: {risk_level}
Expected Brake: {scenario.expected_brake}
Difficulty: {scenario.difficulty}/10
Edge Factors: {scenario.metadata.get("edge_factors", [])}

Output ONLY valid JSON:
{{
  "pattern": "semantic pattern or regex to detect this violation",
  "action": "BLOCK|WARN|LOG",
  "confidence": 0.0-1.0,
  "reasoning": "why this pattern catches the violation",
  "false_positive_indicators": ["what might trigger false positives"],
  "coverage_gaps": ["what this rule might miss"]
}}

Higher difficulty scenarios should have more nuanced patterns.
Confidence should reflect how reliably the pattern catches true violations."""

        result = self._call_minions(prompt, "task")

        try:
            response_text = result.get("response", "{}")
            if isinstance(response_text, str):
                if "```json" in response_text:
                    response_text = response_text.split("```json")[1].split("```")[0]
                elif "```" in response_text:
                    response_text = response_text.split("```")[1].split("```")[0]

                data = json.loads(response_text)
            else:
                data = response_text

            # Calculate false positive rate based on indicators
            fp_indicators = data.get("false_positive_indicators", [])
            fp_rate = min(len(fp_indicators) * 0.05, 0.3)

            rule = DetectionRule(
                rule_id=f"ATP_519_{scenario.scenario_id}",
                pattern=data.get("pattern", ""),
                action=data.get("action", "WARN"),
                confidence=float(data.get("confidence", 0.5)),
                scenario_id=scenario.scenario_id,
                reasoning=data.get("reasoning", ""),
                false_positive_rate=fp_rate,
                metadata={"coverage_gaps": data.get("coverage_gaps", []), "risk_level": risk_level},
            )
            return rule

        except (json.JSONDecodeError, KeyError, ValueError) as e:
            return DetectionRule(
                rule_id=f"ATP_519_fallback_{scenario.scenario_id}",
                pattern="",
                action="LOG",
                confidence=0.0,
                scenario_id=scenario.scenario_id,
                reasoning=f"Parse error: {e}",
            )

    def _evaluate_rule(self, rule: DetectionRule) -> bool:
        """Evaluate if rule meets acceptance criteria."""
        # Check confidence threshold
        if rule.confidence < self.confidence_threshold:
            return False

        # Check for empty pattern
        if not rule.pattern or len(rule.pattern) < 10:
            return False

        # Check false positive rate
        return not rule.false_positive_rate > 0.15

    def _adjust_difficulty(self, rule_accepted: bool) -> None:
        """Adjust difficulty based on executor performance."""
        if rule_accepted:
            self.state.success_streak += 1
            self.state.failure_streak = 0

            # Increase difficulty after 3 consecutive successes
            if self.state.success_streak >= 3:
                self.state.difficulty = min(self.state.difficulty + 1, 10)
                self.state.success_streak = 0
                self.stats["difficulty_increases"] += 1
                print(f"///▞ AGENT0 :: Difficulty ↑ to {self.state.difficulty}")
        else:
            self.state.failure_streak += 1
            self.state.success_streak = 0

            # Decrease difficulty after 3 consecutive failures
            if self.state.failure_streak >= 3:
                self.state.difficulty = max(self.state.difficulty - 1, 1)
                self.state.failure_streak = 0
                self.stats["difficulty_decreases"] += 1
                print(f"///▞ AGENT0 :: Difficulty ↓ to {self.state.difficulty}")

    async def evolve(
        self,
        iterations: int | None = None,
        domain: str = "general",
        verbose: bool = True,
    ) -> list[DetectionRule]:
        """Run the co-evolution loop.

        Args:
            iterations: Number of iterations (default: max_iterations)
            domain: Domain focus (general, defense, healthcare, finance)
            verbose: Print progress

        Returns:
            List of accepted detection rules

        """
        iterations = iterations or self.max_iterations

        if verbose:
            print(f"\n///▞ AGENT0 :: Starting evolution ({iterations} iterations)")
            print(f"///▞ AGENT0 :: Domain: {domain}")
            print("=" * 60)

        for i in range(iterations):
            self.state.iteration = i + 1

            # Curriculum agent generates scenario
            scenario = await self.curriculum_agent(self.state.difficulty, domain)

            # Executor agent generates rule
            rule = await self.executor_agent(scenario)

            # Evaluate rule
            accepted = self._evaluate_rule(rule)

            if accepted:
                self.state.rules_generated.append(rule)
                self.stats["rules_accepted"] += 1
            else:
                self.stats["rules_rejected"] += 1

            # Adjust difficulty
            self._adjust_difficulty(accepted)

            if verbose and (i + 1) % 10 == 0:
                print(
                    f"///▞ AGENT0 :: Iteration {i + 1}/{iterations} | "
                    f"Difficulty: {self.state.difficulty} | "
                    f"Rules: {len(self.state.rules_generated)}",
                )

        if verbose:
            print("=" * 60)
            print("///▞ AGENT0 :: Evolution complete")
            print(f"///▞ AGENT0 :: Rules generated: {len(self.state.rules_generated)}")

        return self.state.rules_generated

    def get_stats(self) -> dict[str, Any]:
        """Get evolution statistics."""
        elapsed = (datetime.now() - self.stats["start_time"]).total_seconds()

        return {
            "iterations": self.state.iteration,
            "current_difficulty": self.state.difficulty,
            "rules_accepted": self.stats["rules_accepted"],
            "rules_rejected": self.stats["rules_rejected"],
            "acceptance_rate": (
                self.stats["rules_accepted"]
                / max(self.stats["rules_accepted"] + self.stats["rules_rejected"], 1)
            ),
            "curriculum_calls": self.stats["curriculum_calls"],
            "executor_calls": self.stats["executor_calls"],
            "difficulty_increases": self.stats["difficulty_increases"],
            "difficulty_decreases": self.stats["difficulty_decreases"],
            "elapsed_seconds": elapsed,
            "rules_per_minute": (self.stats["rules_accepted"] / max(elapsed / 60, 1)),
        }

    def export_rules(self, output_path: str) -> None:
        """Export generated rules to JSON file."""
        rules_data = []
        for rule in self.state.rules_generated:
            rules_data.append(
                {
                    "rule_id": rule.rule_id,
                    "pattern": rule.pattern,
                    "action": rule.action,
                    "confidence": rule.confidence,
                    "scenario_id": rule.scenario_id,
                    "reasoning": rule.reasoning,
                    "false_positive_rate": rule.false_positive_rate,
                    "metadata": rule.metadata,
                },
            )

        with open(output_path, "w") as f:
            json.dump(
                {
                    "generated_at": datetime.now().isoformat(),
                    "stats": self.get_stats(),
                    "rules": rules_data,
                },
                f,
                indent=2,
            )

        print(f"///▞ AGENT0 :: Exported {len(rules_data)} rules to {output_path}")


# Convenience function
def create_agent0(
    minions_url: str = "http://localhost:8600",
    max_iterations: int = 100,
) -> Agent0POC:
    """Create an Agent0 instance."""
    return Agent0POC(minions_url=minions_url, max_iterations=max_iterations)


# Standalone execution
if __name__ == "__main__":

    async def main():
        # Create Agent0 instance
        agent = Agent0POC(max_iterations=20)  # Start small for POC

        # Run evolution
        rules = await agent.evolve(domain="defense", verbose=True)

        # Print results
        print("\n" + "=" * 60)
        print("GENERATED RULES:")
        print("=" * 60)
        for rule in rules[:5]:  # Show first 5
            print(f"\nRule: {rule.rule_id}")
            print(f"  Pattern: {rule.pattern[:80]}...")
            print(f"  Action: {rule.action}")
            print(f"  Confidence: {rule.confidence:.2f}")

        # Print stats
        print("\n" + "=" * 60)
        print("STATISTICS:")
        print("=" * 60)
        stats = agent.get_stats()
        for key, value in stats.items():
            if isinstance(value, float):
                print(f"  {key}: {value:.4f}")
            else:
                print(f"  {key}: {value}")

        # Export rules
        agent.export_rules("/tmp/agent0_rules.json")

    asyncio.run(main())
