"""UNGPT Pipeline - Minimal working version
10 Gemini instances → Git Push → PR
"""

import asyncio
import os
from dataclasses import dataclass
from datetime import datetime


@dataclass
class Atom:
    id: str
    content: str
    tests: list[str] = None

    def __post_init__(self):
        self.tests = self.tests or []


@dataclass
class CodeResult:
    atom_id: str
    code: str
    pr_url: str | None = None
    success: bool = False


class UngptPipeline:
    def __init__(self):
        self.project_id = os.getenv("GCP_PROJECT_ID", "acquired-jet-478701-b3")
        self.repo = "ShadowTag-v2/ShadowTag-v2-fastapi-services"

    async def run(self, task: str) -> list[CodeResult]:
        """Run pipeline: decompose → generate → PR"""
        print(f"\n{'=' * 50}")
        print(f"UNGPT Pipeline - {datetime.utcnow().isoformat()}")
        print(f"{'=' * 50}\n")

        # 1. Decompose task
        atoms = await self._decompose(task)
        print(f"📥 Decomposed into {len(atoms)} atoms")

        # 2. Generate code for each
        results = []
        for atom in atoms:
            result = await self._generate_and_pr(atom)
            results.append(result)
            if result.pr_url:
                print(f"✅ PR: {result.pr_url}")

        return results

    async def _decompose(self, task: str) -> list[Atom]:
        """Break task into atoms using Gemini"""
        try:
            import vertexai
            from vertexai.generative_models import GenerativeModel

            vertexai.init(project=self.project_id, location="us-central1")
            model = GenerativeModel("gemini-2.0-flash-exp")

            prompt = f"""Break this task into 1-3 atomic coding tasks:
{task}

Return JSON array: [{{"id": "unique_id", "content": "task description"}}]
Return ONLY the JSON."""

            response = model.generate_content(prompt)
            import json

            raw = response.text.replace("```json", "").replace("```", "").strip()
            tasks = json.loads(raw)
            return [Atom(id=t["id"][:12], content=t["content"]) for t in tasks[:3]]
        except:
            return [Atom(id="main", content=task)]

    async def _generate_and_pr(self, atom: Atom) -> CodeResult:
        """Generate code and create PR"""
        try:
            import vertexai
            from vertexai.generative_models import GenerativeModel

            vertexai.init(project=self.project_id, location="us-central1")
            model = GenerativeModel("gemini-2.0-flash-exp")

            prompt = f"""Write Python code for: {atom.content}
Output ONLY the code, no explanations."""

            response = model.generate_content(prompt)
            code = response.text.replace("```python", "").replace("```", "").strip()

            # Write and create PR
            pr_url = await self._create_pr(atom, code)

            return CodeResult(atom_id=atom.id, code=code, pr_url=pr_url, success=bool(pr_url))
        except Exception:
            return CodeResult(atom_id=atom.id, code="", success=False)

    async def _create_pr(self, atom: Atom, code: str) -> str | None:
        """Write code, commit, push, create PR"""
        branch = f"ungpt/{atom.id}"
        file_path = f"src/generated/{atom.id}.py"
        full_path = f"/Users/pikeymickey/ShadowTag-v2-fastapi-services/{file_path}"

        try:
            # Ensure dir exists
            os.makedirs(os.path.dirname(full_path), exist_ok=True)

            # Write code
            with open(full_path, "w") as f:
                f.write(code)

            # Git operations
            cmds = f"""
cd /Users/pikeymickey/ShadowTag-v2-fastapi-services && \
git checkout main && \
git checkout -b {branch} 2>/dev/null || git checkout {branch} && \
git add {file_path} && \
git commit -m "feat: {atom.content[:50]}" && \
git push -u origin {branch}
"""
            proc = await asyncio.create_subprocess_shell(
                cmds,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            await proc.communicate()

            if proc.returncode != 0:
                return None

            # Create PR
            pr_proc = await asyncio.create_subprocess_exec(
                "gh",
                "pr",
                "create",
                "--repo",
                self.repo,
                "--head",
                branch,
                "--base",
                "main",
                "--title",
                f"feat: {atom.content[:60]}",
                "--body",
                f"Generated by UNGPT\n\nAtom: {atom.id}",
                stdout=asyncio.subprocess.PIPE,
            )
            stdout, _ = await pr_proc.communicate()

            if pr_proc.returncode == 0:
                return stdout.decode().strip()
            return None
        except:
            return None


if __name__ == "__main__":

    async def main():
        p = UngptPipeline()
        results = await p.run("Create a health check endpoint")
        print(f"\nResults: {len([r for r in results if r.success])} PRs created")

    asyncio.run(main())
