#!/usr/bin/env python3
"""
Coverage Report Generator

Generates detailed coverage reports with file-level and function-level
breakdowns. Outputs JSON format for consumption by hooks and agents.

Usage:
    uv run python .claude/scripts/coverage-report.py
    uv run python .claude/scripts/coverage-report.py --format json
    uv run python .claude/scripts/coverage-report.py --threshold 98
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


def run_coverage(threshold: int | None = None) -> dict[str, Any]:
    """
    Run pytest with coverage and parse results.

    Args:
        threshold: Coverage threshold percentage (e.g., 98)

    Returns:
        Coverage report data
    """
    cmd = ["uv", "run", "pytest", "--cov", "--cov-report=json", "--cov-report=term-missing"]

    if threshold:
        cmd.append(f"--cov-fail-under={threshold}")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=False, cwd=Path.cwd())

        # Read coverage.json generated by pytest-cov
        coverage_file = Path.cwd() / "coverage.json"

        if not coverage_file.exists():
            return {
                "error": "Coverage file not found",
                "stdout": result.stdout,
                "stderr": result.stderr,
            }

        with coverage_file.open() as f:
            coverage_data = json.load(f)

        # Parse total coverage
        total_coverage = coverage_data.get("totals", {}).get("percent_covered", 0)

        # Parse file-level coverage
        files = {}
        for filepath, file_data in coverage_data.get("files", {}).items():
            summary = file_data.get("summary", {})
            missing = file_data.get("missing_lines", [])

            files[filepath] = {
                "coverage": summary.get("percent_covered", 0),
                "lines_total": summary.get("num_statements", 0),
                "lines_covered": summary.get("covered_lines", 0),
                "lines_missing": missing,
                "lines_missing_count": len(missing),
            }

        return {
            "total_coverage": round(total_coverage, 2),
            "threshold": threshold,
            "passed": result.returncode == 0,
            "files": files,
            "timestamp": subprocess.check_output(["date", "-u", "+%Y-%m-%dT%H:%M:%SZ"])
            .decode()
            .strip(),
        }

    except Exception as e:
        return {"error": str(e)}


def format_text_report(coverage_data: dict[str, Any]) -> str:
    """
    Format coverage data as human-readable text.

    Args:
        coverage_data: Coverage report data

    Returns:
        Formatted text report
    """
    lines = []
    lines.append("=" * 80)
    lines.append("COVERAGE REPORT")
    lines.append("=" * 80)
    lines.append("")

    if "error" in coverage_data:
        lines.append(f"ERROR: {coverage_data['error']}")
        return "\n".join(lines)

    total = coverage_data["total_coverage"]
    threshold = coverage_data.get("threshold", 0)
    passed = coverage_data["passed"]

    lines.append(f"Total Coverage: {total}%")

    if threshold:
        status = "✅ PASSED" if passed else "❌ FAILED"
        lines.append(f"Threshold: {threshold}% - {status}")

    lines.append("")
    lines.append("FILE BREAKDOWN")
    lines.append("-" * 80)

    # Sort files by coverage (lowest first)
    sorted_files = sorted(coverage_data["files"].items(), key=lambda x: x[1]["coverage"])

    for filepath, file_data in sorted_files:
        cov = file_data["coverage"]
        missing_count = file_data["lines_missing_count"]

        status_icon = "✅" if cov >= (threshold or 98) else "❌"

        lines.append(f"{status_icon} {filepath}")
        lines.append(f"   Coverage: {cov}%")
        lines.append(f"   Lines: {file_data['lines_covered']}/{file_data['lines_total']}")

        if missing_count > 0:
            missing = file_data["lines_missing"]
            # Group consecutive lines
            grouped = group_consecutive(missing)
            lines.append(f"   Missing: {grouped}")

        lines.append("")

    return "\n".join(lines)


def group_consecutive(numbers: list[int]) -> str:
    """
    Group consecutive numbers into ranges.

    Example: [1, 2, 3, 5, 7, 8, 9] -> "1-3, 5, 7-9"

    Args:
        numbers: List of line numbers

    Returns:
        Formatted string with ranges
    """
    if not numbers:
        return ""

    numbers = sorted(numbers)
    groups = []
    start = numbers[0]
    end = numbers[0]

    for num in numbers[1:]:
        if num == end + 1:
            end = num
        else:
            if start == end:
                groups.append(str(start))
            else:
                groups.append(f"{start}-{end}")
            start = num
            end = num

    # Add final group
    if start == end:
        groups.append(str(start))
    else:
        groups.append(f"{start}-{end}")

    return ", ".join(groups)


def main():
    parser = argparse.ArgumentParser(description="Generate detailed coverage reports")
    parser.add_argument(
        "--format",
        choices=["text", "json"],
        default="text",
        help="Output format (default: text)",
    )
    parser.add_argument(
        "--threshold",
        type=int,
        default=98,
        help="Coverage threshold percentage (default: 98)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output file path (default: stdout)",
    )

    args = parser.parse_args()

    # Run coverage
    coverage_data = run_coverage(threshold=args.threshold)

    # Format output
    if args.format == "json":
        output = json.dumps(coverage_data, indent=2)
    else:
        output = format_text_report(coverage_data)

    # Write output
    if args.output:
        args.output.write_text(output)
        print(f"Coverage report written to {args.output}")
    else:
        print(output)

    # Exit with failure if coverage below threshold
    if not coverage_data.get("passed", True):
        sys.exit(1)


if __name__ == "__main__":
    main()
