apiVersion: v1
kind: ServiceAccount
metadata:
  name: cor17-sa
  namespace: cor17
  annotations:
    iam.gke.io/gcp-service-account: cor17-gke@YOUR_PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cor17-role
  namespace: cor17
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cor17-role-binding
  namespace: cor17
subjects:
- kind: ServiceAccount
  name: cor17-sa
  namespace: cor17
roleRef:
  kind: Role
  name: cor17-role
  apiGroup: rbac.authorization.k8s.io
