# Copyright (c) 2026 ShadowTag, Inc. All rights reserved.

"""AGNT Prompt Speculation Engine.

Ported from: Claude Code speculation.ts (992 lines) + promptSuggestion.ts (524 lines)
Reference: AGNT STATE B Spec P4.2

The Speculation Engine pre-computes nag prompts while the operator reads
the current response. This significantly drops perceived latency because
the nag prompts are already generated by the time the response finishes.

Architecture (derived from CC speculation.ts):
    1. After each agent response, a background "forked agent" runs
       to predict what the operator will type next
    2. Prompt suggestions are generated using context from the conversation
    3. Suggestions are cached and served instantly when the operator accepts
    4. A pipeline chains speculation → suggestion → pre-computation

Key differences from CC implementation:
    - CC uses overlay filesystem isolation for speculative writes (COW)
    - We simplify to prompt-only speculation (no file I/O speculation)
    - CC gates on USER_TYPE === 'ant'; we gate on config flag
    - CC tracks time-saved metrics per session; we do the same
"""

from __future__ import annotations

import contextlib
import hashlib
import logging
import re
import time
import warnings
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

warnings.warn(
    "agnt_tools.speculation_engine is deprecated. "
    "Use 'from speculation_engine import SpeculationEngine, SuggestionManager' instead. "
    "This shim will be removed in v14.0.",
    DeprecationWarning,
    stacklevel=2,
)

# Re-export the new package's public API for backwards compatibility.
# Consumers should migrate to `import speculation_engine` directly.
with contextlib.suppress(ImportError):
    from speculation_engine import (  # noqa: E402, F401
        OverlayFS,
        SpeculationEngine,
        SpeculativeResearchOrchestrator,
        SuggestionManager,
        emit_event,
        read_telemetry_events,
    )

logger = logging.getLogger(__name__)


class SpeculationStatus(StrEnum):
    """Speculation lifecycle states."""

    IDLE = "idle"
    GENERATING = "generating"
    READY = "ready"
    ACCEPTED = "accepted"
    ABORTED = "aborted"
    ERROR = "error"


class SuppressReason(StrEnum):
    """Reasons a suggestion was suppressed (CC promptSuggestion.ts L107-118)."""

    DISABLED = "disabled"
    EARLY_CONVERSATION = "early_conversation"
    LAST_RESPONSE_ERROR = "last_response_error"
    PLAN_MODE = "plan_mode"
    RATE_LIMIT = "rate_limit"
    ABORTED = "aborted"
    EMPTY = "empty"
    FILTERED = "filtered"


# Suggestion filters ported from CC promptSuggestion.ts L354-456
_EVALUATIVE_PATTERN = re.compile(
    r"thanks|thank you|looks good|sounds good|that works|that worked|"
    r"that's all|nice|great|perfect|makes sense|awesome|excellent",
    re.IGNORECASE,
)

_CLAUDE_VOICE_PATTERN = re.compile(
    r"^(let me|i'll|i've|i'm|i can|i would|i think|i notice|"
    r"here's|here is|here are|that's|this is|this will|"
    r"you can|you should|you could|sure,|of course|certainly)",
    re.IGNORECASE,
)

_SILENCE_PATTERN = re.compile(
    r"\bsilence is\b|\bstay(s|ing)? silent\b|^\W*silence\W*$",
    re.IGNORECASE,
)

_META_WRAPPED_PATTERN = re.compile(r"^\(.*\)$|^\[.*\]$")

# Single words that are valid commands (CC L403-424)
_ALLOWED_SINGLE_WORDS = frozenset(
    {
        "yes",
        "yeah",
        "yep",
        "yea",
        "yup",
        "sure",
        "ok",
        "okay",
        "push",
        "commit",
        "deploy",
        "stop",
        "continue",
        "check",
        "exit",
        "quit",
        "no",
    }
)


@dataclass
class PromptSuggestion:
    """A pre-computed prompt suggestion."""

    text: str
    prompt_id: str = "user_intent"
    generated_at: float = field(default_factory=time.time)
    context_hash: str = ""
    shown_at: float = 0.0
    accepted_at: float = 0.0


@dataclass
class SpeculationResult:
    """Result of a speculation cycle."""

    suggestion: PromptSuggestion | None
    status: SpeculationStatus
    generation_time_ms: float = 0.0
    suppress_reason: str | None = None


@dataclass
class SpeculationMetrics:
    """Session-level speculation metrics (CC speculation.ts L759-761)."""

    total_speculations: int = 0
    accepted: int = 0
    aborted: int = 0
    errors: int = 0
    total_time_saved_ms: float = 0.0
    total_generation_time_ms: float = 0.0
    cache_hits: int = 0
    cache_misses: int = 0


class PromptSpeculationEngine:
    """Pre-computes nag prompts to reduce perceived latency.

    Architecture:
        1. Context Analysis: Examines recent conversation to build context
        2. Pattern Matching: Uses task phase + complexity heuristics
        3. Prompt Generation: Pre-computes appropriate nag prompts
        4. Caching: Stores results keyed by context hash
        5. Serving: Returns cached results instantly on request

    The engine implements the CC speculation.ts overlay pattern
    but simplified to prompt-only (no file I/O speculation).
    """

    # Max cached suggestions before eviction
    MAX_CACHE_SIZE = 50
    # Default cache TTL in milliseconds
    DEFAULT_CACHE_MS = 30_000

    def __init__(self, cache_ms: int | None = None) -> None:
        self._cache: dict[str, PromptSuggestion] = {}
        self._cache_ms = cache_ms or self.DEFAULT_CACHE_MS
        self._metrics = SpeculationMetrics()
        self._current_status = SpeculationStatus.IDLE
        self._abort_flag = False

    @property
    def metrics(self) -> SpeculationMetrics:
        """Session-level speculation metrics."""
        return self._metrics

    @property
    def status(self) -> SpeculationStatus:
        """Current speculation lifecycle state."""
        return self._current_status

    def speculate(
        self,
        conversation_context: list[dict[str, Any]],
        task_phase: str = "active",
        complexity: str = "medium",
    ) -> SpeculationResult:
        """Run a speculation cycle to pre-compute nag prompts.

        This is the main entry point, called after each agent response.

        Args:
            conversation_context: Recent conversation messages.
            task_phase: Current task phase (start/active/complete/error).
            complexity: Task complexity (simple/medium/complex/architecture).

        Returns:
            SpeculationResult with the pre-computed suggestion or suppress reason.
        """
        self._metrics.total_speculations += 1
        self._current_status = SpeculationStatus.GENERATING
        start_time = time.time()

        try:
            # Check suppression conditions (CC promptSuggestion.ts L107-118)
            suppress = self._check_suppression(conversation_context, task_phase)
            if suppress:
                self._current_status = SpeculationStatus.IDLE
                return SpeculationResult(
                    suggestion=None,
                    status=SpeculationStatus.IDLE,
                    suppress_reason=suppress,
                )

            # Check cache first
            ctx_hash = self._compute_context_hash(conversation_context, task_phase)
            cached = self._get_cached(ctx_hash)
            if cached:
                self._metrics.cache_hits += 1
                self._current_status = SpeculationStatus.READY
                return SpeculationResult(
                    suggestion=cached,
                    status=SpeculationStatus.READY,
                    generation_time_ms=0.0,
                )

            self._metrics.cache_misses += 1

            # Check abort before generating
            if self._abort_flag:
                self._abort_flag = False
                self._metrics.aborted += 1
                self._current_status = SpeculationStatus.ABORTED
                return SpeculationResult(
                    suggestion=None,
                    status=SpeculationStatus.ABORTED,
                    suppress_reason="aborted",
                )

            # Generate prompts based on task phase and complexity
            prompts = self._generate_nag_prompts(conversation_context, task_phase, complexity)

            generation_ms = (time.time() - start_time) * 1000
            self._metrics.total_generation_time_ms += generation_ms

            if not prompts:
                self._current_status = SpeculationStatus.IDLE
                return SpeculationResult(
                    suggestion=None,
                    status=SpeculationStatus.IDLE,
                    generation_time_ms=generation_ms,
                    suppress_reason="no_prompts",
                )

            # Create suggestion from first prompt
            suggestion = PromptSuggestion(
                text=prompts[0],
                context_hash=ctx_hash,
            )

            # Cache it
            self._set_cached(ctx_hash, suggestion)

            self._current_status = SpeculationStatus.READY
            return SpeculationResult(
                suggestion=suggestion,
                status=SpeculationStatus.READY,
                generation_time_ms=generation_ms,
            )

        except Exception as e:
            self._metrics.errors += 1
            self._current_status = SpeculationStatus.ERROR
            logger.warning("Speculation error: %s", e)
            return SpeculationResult(
                suggestion=None,
                status=SpeculationStatus.ERROR,
                suppress_reason=f"error:{e!s}",
            )

    def accept(self, suggestion: PromptSuggestion) -> float:
        """Accept a speculation result. Returns time saved in ms.

        Mirrors CC acceptSpeculation (speculation.ts L717-798).
        """
        now = time.time()
        suggestion.accepted_at = now
        time_saved_ms = (now - suggestion.generated_at) * 1000
        self._metrics.accepted += 1
        self._metrics.total_time_saved_ms += time_saved_ms
        self._current_status = SpeculationStatus.ACCEPTED
        logger.info("Speculation accepted: saved %.1fms", time_saved_ms)
        return time_saved_ms

    def abort(self) -> None:
        """Abort current speculation. Mirrors CC abortSpeculation."""
        self._abort_flag = True
        self._metrics.aborted += 1
        self._current_status = SpeculationStatus.ABORTED

    def reset(self) -> None:
        """Reset to idle state."""
        self._current_status = SpeculationStatus.IDLE
        self._abort_flag = False

    # --- Prompt Generation (Nag Protocol Integration) ---

    def _generate_nag_prompts(
        self,
        context: list[dict[str, Any]],
        task_phase: str,
        complexity: str,
    ) -> list[str]:
        """Generate nag prompts based on task phase and complexity.

        Implements the complexity-proportional prompt counts from GEMINI.md:
        | Task Phase            | Prompt Count |
        |----------------------|--------------|
        | Simple follow-up     | 5–8          |
        | Active implementation| 8–14         |
        | Architecture decision| 14–18        |
        | Session start, audit | 18–22        |
        """
        # Determine prompt count from complexity
        count_ranges = {
            "simple": (5, 8),
            "medium": (8, 14),
            "complex": (14, 18),
            "architecture": (18, 22),
        }
        min_count, max_count = count_ranges.get(complexity, (8, 14))

        # Analyze context to determine appropriate prompts
        prompts = self._analyze_context_for_prompts(context, task_phase, min_count, max_count)

        # Filter through CC's suggestion filter pipeline
        return [p for p in prompts if not self._should_filter(p)]

    def _analyze_context_for_prompts(
        self,
        context: list[dict[str, Any]],
        task_phase: str,
        min_count: int,
        max_count: int,
    ) -> list[str]:
        """Analyze conversation context to generate relevant prompts.

        Uses the CC SUGGESTION_PROMPT pattern (promptSuggestion.ts L258-287):
        - Look at user's recent messages and original request
        - Predict what THEY would type next
        - Be specific: "run the tests" beats "continue"
        """
        # Extract last few messages for context
        recent = context[-5:] if len(context) >= 5 else context
        last_msg = recent[-1] if recent else {}
        last_content = str(last_msg.get("content", ""))[:200]

        # Phase-aware prompt templates
        phase_prompts: dict[str, list[str]] = {
            "start": [
                "Run the full test suite to establish baseline",
                "Audit current git status and pending changes",
                "Check MCP server health across all 5 servers",
                "Review the risk register for open items",
                "Run dead-code analysis with ruff F401/F841",
                "Verify Firebase CLI authentication status",
                "Check Cloud Run revision health",
                "Audit skill fleet for gaps",
                "Run egress scan on pending changes",
                "Check Lighthouse scores on staging",
                "Review pending ehanc69 sub-repo status",
                "Validate Firestore rules deployment",
                "Run betterleaks secret scan",
                "Check GitHub App authentication",
                "Audit KI system for stale entries",
                "Run dream consolidation daemon",
                "Verify Stripe webhook connectivity",
                "Check DNS configuration status",
                "Review CSP headers on production",
                "Audit GCP API usage and quotas",
                "Run pnkln_evolve for skill evolution",
                "Check context budget utilization",
            ],
            "active": [
                "Run lint on modified files",
                "Run the test suite",
                "Check for type errors",
                "Verify the implementation against spec",
                "Run ruff check --fix on changed files",
                "Stage and commit the changes",
                "Push via GitHub App auth",
                "Run Lighthouse on the changes",
                "Check for dead code in modified files",
                "Verify no secrets in staged files",
                "Run biome lint on TypeScript changes",
                "Check import ordering",
                "Review the diff before committing",
                "Update documentation for changes",
            ],
            "complete": [
                "Run the full test suite for verification",
                "Stage and commit all changes",
                "Push to upstream via Omega Sync",
                "Run post-commit validation",
                "Update the risk register",
                "Archive completed task documentation",
                "Run betterleaks on the final state",
                "Check CI/CD pipeline status",
            ],
            "error": [
                "Check the error logs for details",
                "Run the failing test in isolation",
                "Check git status for conflicts",
                "Review recent changes for regression",
                "Run systematic debugging workflow",
                "Check MCP server connectivity",
                "Verify environment variables",
                "Roll back the last change",
            ],
        }

        base_prompts = phase_prompts.get(task_phase, phase_prompts["active"])

        # Context-aware filtering
        filtered: list[str] = []
        for prompt in base_prompts:
            if len(filtered) >= max_count:
                break
            # Don't suggest what was just done
            if last_content and prompt.lower() in last_content.lower():
                continue
            filtered.append(prompt)

        # Pad to minimum if needed
        while len(filtered) < min_count and base_prompts:
            for p in phase_prompts.get("active", []):
                if p not in filtered and len(filtered) < min_count:
                    filtered.append(p)
            break

        return filtered[:max_count]

    # --- Suggestion Filtering (CC promptSuggestion.ts L354-456) ---

    @staticmethod
    def _should_filter(suggestion: str) -> bool:
        """Apply CC's suggestion filter pipeline."""
        if not suggestion:
            return True

        lower = suggestion.lower()
        words = suggestion.strip().split()
        word_count = len(words)

        # Done
        if lower == "done":
            return True
        # Meta text
        if lower in ("nothing found", "nothing found.") or lower.startswith(("nothing to suggest", "no suggestion")):
            return True
        if _SILENCE_PATTERN.search(lower):
            return True
        # Meta wrapped
        if _META_WRAPPED_PATTERN.match(suggestion):
            return True
        # Error messages
        if lower.startswith(("api error:", "prompt is too long", "request timed out", "invalid api key")):
            return True
        # Too few words (unless slash command or allowed single word)
        if word_count < 2:
            if not suggestion.startswith("/") and lower not in _ALLOWED_SINGLE_WORDS:
                return True
        # Too many words or too long
        if word_count > 12 or len(suggestion) >= 100:
            return True
        # Multiple sentences
        if re.search(r"[.!?]\s+[A-Z]", suggestion):
            return True
        # Formatting
        if re.search(r"[\n*]|\*\*", suggestion):
            return True
        # Evaluative
        if _EVALUATIVE_PATTERN.search(lower):
            return True
        # Claude voice
        return bool(_CLAUDE_VOICE_PATTERN.match(suggestion))

    # --- Suppression Checks (CC promptSuggestion.ts L107-118) ---

    @staticmethod
    def _check_suppression(
        context: list[dict[str, Any]],
        task_phase: str,
    ) -> str | None:
        """Check if suggestion generation should be suppressed."""
        try:
            from config.feature_flags import flags

            if not flags.is_enabled("telemetry_enabled"):
                return SuppressReason.DISABLED.value
        except ImportError:
            pass  # Feature flags not available (e.g., during isolated test runs)

        # Need at least 2 assistant turns
        assistant_count = sum(1 for m in context if m.get("role") == "assistant")
        if assistant_count < 1:
            return SuppressReason.EARLY_CONVERSATION.value

        # Last message was an error
        if context:
            last = context[-1]
            if last.get("is_error"):
                return SuppressReason.LAST_RESPONSE_ERROR.value

        # Plan mode
        if task_phase == "planning":
            return SuppressReason.PLAN_MODE.value

        return None

    # --- Cache Management ---

    def _compute_context_hash(
        self,
        context: list[dict[str, Any]],
        task_phase: str,
    ) -> str:
        """Compute a hash of the context for caching."""
        # Use last 3 messages + phase for cache key
        recent = context[-3:] if len(context) >= 3 else context
        key_parts = [task_phase]
        for msg in recent:
            key_parts.append(f"{msg.get('role', '')}:{str(msg.get('content', ''))[:100]}")
        key_str = "|".join(key_parts)
        return hashlib.sha256(key_str.encode()).hexdigest()[:16]

    def _get_cached(self, ctx_hash: str) -> PromptSuggestion | None:
        """Get a cached suggestion if it exists and hasn't expired."""
        if ctx_hash not in self._cache:
            return None
        suggestion = self._cache[ctx_hash]
        age_ms = (time.time() - suggestion.generated_at) * 1000
        if age_ms > self._cache_ms:
            del self._cache[ctx_hash]
            return None
        return suggestion

    def _set_cached(self, ctx_hash: str, suggestion: PromptSuggestion) -> None:
        """Cache a suggestion, evicting oldest if at capacity."""
        if len(self._cache) >= self.MAX_CACHE_SIZE:
            oldest_key = min(self._cache, key=lambda k: self._cache[k].generated_at)
            del self._cache[oldest_key]
        self._cache[ctx_hash] = suggestion

    def clear_cache(self) -> int:
        """Clear the suggestion cache. Returns count of evicted entries."""
        count = len(self._cache)
        self._cache.clear()
        return count

    def format_metrics(self) -> str:
        """Format session metrics as a readable string."""
        m = self._metrics
        hit_rate = m.cache_hits / (m.cache_hits + m.cache_misses) * 100 if (m.cache_hits + m.cache_misses) > 0 else 0
        return (
            f"Speculation Metrics:\n"
            f"  Total: {m.total_speculations} | "
            f"Accepted: {m.accepted} | "
            f"Aborted: {m.aborted} | "
            f"Errors: {m.errors}\n"
            f"  Time Saved: {m.total_time_saved_ms:.0f}ms | "
            f"Gen Time: {m.total_generation_time_ms:.0f}ms\n"
            f"  Cache: {m.cache_hits} hits / "
            f"{m.cache_misses} misses ({hit_rate:.0f}% hit rate)"
        )
