#!/bin/bash
set -e

echo '🚀 Stripe Integration Setup'
echo ''
echo '✅ Files already created:'
ls -lh scripts/setup_stripe_products.py api/routes/subscription.py public/pricing.html
echo ''
echo '🔑 NEXT STEPS:'
echo ''
echo '1. Get Stripe API keys:'
echo '   https://dashboard.stripe.com/test/apikeys'
echo ''
echo '2. Add to .env file:'
echo '   STRIPE_SECRET_KEY=sk_test_...'
echo '   STRIPE_PUBLISHABLE_KEY=pk_test_...'
echo ''
echo '3. Create products:'
echo '   python3 scripts/setup_stripe_products.py'
echo ''
echo '4. Copy price IDs to .env'
echo ''
echo '5. Add to main.py:'
echo '   from api.routes.subscription import router as subscription_router'
echo '   app.include_router(subscription_router)'
echo ''
echo '6. Test:'
echo '   uvicorn main:app --reload'
echo '   open http://localhost:8000/public/pricing.html'
echo ''
echo '📊 Target: $200 MRR by Week 2'
