import json
import os
from pathlib import Path


def create_single_repo_workspace(base_path, name):
    """
    Creates an Apigee single-repository workspace structure with boilerplate.
    """
    root = Path(base_path) / name
    target = root / "src" / "main" / "apigee"
    folders = ["apiproxies", "environments", "sharedflows", "tests"]

    for folder in folders:
        (target / folder).mkdir(parents=True, exist_ok=True)

    # 1. Add README.md
    with open(root / "README.md", "w") as f:
        f.write(
            f"# Apigee Workspace: {name}\n\nGenerated by Antigravity // Pinkln Ultrathink.\n\n## Structure\n- `src/main/apigee/`: Core Apigee artifacts.\n- `tests/`: BDD/Unit tests.\n"
        )

    # 2. Add starter-proxy boilerplate
    proxy_name = "starter-proxy"
    proxy_root = target / "apiproxies" / proxy_name
    (proxy_root / "proxies").mkdir(parents=True, exist_ok=True)
    (proxy_root / "targets").mkdir(parents=True, exist_ok=True)

    with open(proxy_root / f"{proxy_name}.xml", "w") as f:
        f.write(
            f'<APIProxy name="{proxy_name}">\n    <DisplayName>{proxy_name}</DisplayName>\n    <Description>Auto-generated by Antigravity</Description>\n</APIProxy>'
        )

    # 3. Add Judge #6 governance stub
    with open(root / "judge_six.json", "w") as f:
        json.dump(
            {
                "mission": f"Manage Apigee proxy: {name}",
                "enforcement": "SOP-C",
                "confidence_threshold": 0.75,
            },
            f,
            indent=4,
        )

    return str(target)


def create_multi_repo_workspace(base_path, name, proxies=None):
    """
    Creates an Apigee multi-repository workspace with boilerplate.
    """
    root = Path(base_path) / name
    root.mkdir(parents=True, exist_ok=True)
    workspace_file = root / f"{name}.code-workspace"

    folders = []
    if proxies:
        for p in proxies:
            folders.append({"name": p, "path": str(Path(root) / p)})
    else:
        folders = [
            {"name": "auth-proxy", "path": "auth-proxy"},
            {"name": "dev-env", "path": "dev-env"},
        ]

    workspace_data = {"folders": folders, "settings": {"apigee.workspace.type": "multi-repo"}}

    with open(workspace_file, "w") as f:
        json.dump(workspace_data, f, indent=4)

    # Ensure directories exist and add README
    for folder in folders:
        f_path = root / folder["path"]
        f_path.mkdir(parents=True, exist_ok=True)
        with open(f_path / "README.md", "w") as f:
            f.write(f"# {folder['name']}\nPart of {name} workspace.")

    return str(workspace_file)


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 2:
        mode = sys.argv[1]
        name = sys.argv[2]
        cwd = os.getcwd()
        if mode == "single":
            path = create_single_repo_workspace(cwd, name)
            print(f"✅ Created Single-Repo Workspace at: {path}")
        elif mode == "multi":
            path = create_multi_repo_workspace(cwd, name)
            print(f"✅ Created Multi-Repo Workspace: {path}")
        else:
            print("Usage: apigee_workspace.py [single|multi] [name]")
