// This snippet file was generated by processing the source file:
// ./database-next/lists-of-data.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

import { getAuth } from 'firebase/auth';
// [START rtdb_social_most_starred_modular]
import { getDatabase, orderByChild, query, ref } from 'firebase/database';

const db = getDatabase();
const auth = getAuth();

const myUserId = auth.currentUser.uid;
const topUserPostsRef = query(ref(db, 'user-posts/' + myUserId), orderByChild('starCount'));
// [END rtdb_social_most_starred_modular]
