# Copyright (c) 2026 ShadowTag, Inc. All rights reserved.

"""Three-Layer Context Memory — memory_indexer.py

All context must traverse this module before entering the agent's
context window. Maintains a hyper-lightweight pointer table (MEMORY.md)
instead of raw transcripts.

Architecture:
  Layer 1: Hot pointers  → MEMORY.md (file paths + line ranges + summaries)
  Layer 2: Warm vectors   → LanceDB workspace_knowledge table
  Layer 3: Cold archive   → .beads/session_state.jsonl

No raw transcripts in context window. Ever.
"""

from __future__ import annotations

import json
import hashlib
from datetime import datetime, UTC
from pathlib import Path
from typing import Any


MEMORY_MD_PATH = Path("MEMORY.md")
SESSION_STATE_PATH = Path(".beads/session_state.jsonl")
MAX_HOT_ENTRIES = 50
MAX_SUMMARY_CHARS = 200


def _hash_content(content: str) -> str:
  """SHA-256 fingerprint for dedup."""
  return hashlib.sha256(content.encode()).hexdigest()[:16]


def index_file_context(
  file_path: str,
  start_line: int,
  end_line: int,
  summary: str,
  tags: list[str] | None = None,
) -> dict[str, Any]:
  """Add a file context pointer to the hot layer (MEMORY.md).

  Args:
      file_path: Absolute or relative path to the source file.
      start_line: First relevant line (1-indexed).
      end_line: Last relevant line (1-indexed).
      summary: ≤200 char summary of what this context contains.
      tags: Optional classification tags (e.g., ["security", "api"]).

  Returns:
      The pointer entry dict that was written.
  """
  summary = summary[:MAX_SUMMARY_CHARS]
  entry = {
    "file": file_path,
    "lines": f"L{start_line}-L{end_line}",
    "summary": summary,
    "tags": tags or [],
    "indexed_at": datetime.now(UTC).isoformat(),
    "fingerprint": _hash_content(f"{file_path}:{start_line}:{end_line}"),
  }

  # Append to hot layer
  _append_hot_pointer(entry)

  # Append to cold archive
  _append_cold_archive(entry)

  return entry


def _append_hot_pointer(entry: dict[str, Any]) -> None:
  """Append pointer to MEMORY.md, enforcing MAX_HOT_ENTRIES."""
  entries = _load_hot_pointers()

  # Dedup by fingerprint
  existing_fps = {e.get("fingerprint") for e in entries}
  if entry["fingerprint"] in existing_fps:
    return

  entries.append(entry)

  # Evict oldest if over limit
  if len(entries) > MAX_HOT_ENTRIES:
    entries = entries[-MAX_HOT_ENTRIES:]

  _write_hot_pointers(entries)


def _load_hot_pointers() -> list[dict[str, Any]]:
  """Parse MEMORY.md into structured entries."""
  if not MEMORY_MD_PATH.exists():
    return []

  entries = []
  current_block: dict[str, Any] = {}
  for line in MEMORY_MD_PATH.read_text().splitlines():
    if line.startswith("- **"):
      if current_block:
        entries.append(current_block)
      # Parse: - **file_path** L1-L50 | summary | [tags]
      current_block = {"raw": line}
    elif line.startswith("  ") and current_block:
      current_block["raw"] += "\n" + line

  if current_block:
    entries.append(current_block)

  return entries


def _write_hot_pointers(entries: list[dict[str, Any]]) -> None:
  """Write structured entries back to MEMORY.md."""
  MEMORY_MD_PATH.parent.mkdir(parents=True, exist_ok=True)

  lines = [
    "# MEMORY.md — Hot Pointer Table",
    f"<!-- Auto-generated by memory_indexer.py | {datetime.now(UTC).isoformat()} -->",
    f"<!-- {len(entries)} entries (max {MAX_HOT_ENTRIES}) -->",
    "",
  ]

  for entry in entries:
    if "raw" in entry:
      lines.append(entry["raw"])
    else:
      tags_str = ", ".join(entry.get("tags", []))
      lines.append(
        f"- **{entry['file']}** {entry['lines']} | {entry['summary']} | [{tags_str}]"
      )

  MEMORY_MD_PATH.write_text("\n".join(lines) + "\n")


def _append_cold_archive(entry: dict[str, Any]) -> None:
  """Append to .beads/session_state.jsonl for cold storage."""
  SESSION_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
  with SESSION_STATE_PATH.open("a") as f:
    f.write(json.dumps(entry, default=str) + "\n")


def get_hot_context() -> str:
  """Return the full MEMORY.md content for injection into context."""
  if MEMORY_MD_PATH.exists():
    return MEMORY_MD_PATH.read_text()
  return ""


def clear_hot_context() -> None:
  """Reset MEMORY.md (e.g., on session start)."""
  _write_hot_pointers([])


if __name__ == "__main__":
  # Self-test
  result = index_file_context(
    file_path="apps/counselconduit/src/main.py",
    start_line=1,
    end_line=50,
    summary="CounselConduit FastAPI entrypoint with RBAC middleware",
    tags=["api", "security"],
  )
  print(f"Indexed: {result}")
  print(f"Hot context:\n{get_hot_context()}")
