#!/usr/bin/env bash
# guardrail-annotation-audit.sh — Verify <!-- GUARDRAIL --> annotations on moderate+ risk skills
# Part of MONOREPO_OS SkillOps governance layer
set -euo pipefail

REPORT_DIR=".reports/skills"
REPORT_FILE="${REPORT_DIR}/guardrail_annotation_audit.md"
TRIAGE_FILE="${REPORT_DIR}/unsafe_findings_triage.md"

mkdir -p "$REPORT_DIR"

# Skills classified as moderate or actual risk in the triage
MODERATE_RISK_SKILLS=(
  "repo-mass-reduction"
  "yolo-mode-operator"
  "high-risk-command-scanner"
  "control-plane-doctrine"
  "tacsop-operational-patterns"
  "daemon-fleet-manager"
  "temporal-rollback-doctrine"
  "cor-cursor-vdi"
  "anti-vibe-code-enforcer"
  "mcp-github"
  "cor-deployment-operations"
  "runtime-health-watchdog"
)

total=0
annotated=0
missing=()

for skill in "${MODERATE_RISK_SKILLS[@]}"; do
  total=$((total + 1))
  # Search both workspace and global skill locations
  found=0
  for base in ".agents/skills" "$HOME/.gemini/antigravity/skills"; do
    skill_file="${base}/${skill}/SKILL.md"
    if [[ -f "$skill_file" ]]; then
      if grep -q '<!-- GUARDRAIL' "$skill_file" 2>/dev/null; then
        annotated=$((annotated + 1))
        found=1
        break
      else
        found=2  # Found file but no annotation
        break
      fi
    fi
  done
  if [[ $found -ne 1 ]]; then
    missing+=("$skill")
  fi
done

# Generate report
cat > "$REPORT_FILE" <<EOF
# GUARDRAIL Annotation Audit Report

**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Total moderate+ risk skills:** $total
**Annotated:** $annotated
**Missing annotations:** $((total - annotated))

## Status

$(if [[ ${#missing[@]} -eq 0 ]]; then
  echo "✅ All moderate+ risk skills have GUARDRAIL annotations."
else
  echo "⚠️ The following skills are missing GUARDRAIL annotations:"
  echo ""
  for m in "${missing[@]}"; do
    echo "- \`$m\`"
  done
fi)

## Audited Skills

| Skill | Status |
|-------|--------|
$(for skill in "${MODERATE_RISK_SKILLS[@]}"; do
  if printf '%s\n' "${missing[@]}" | grep -qx "$skill" 2>/dev/null; then
    echo "| \`$skill\` | ❌ Missing |"
  else
    echo "| \`$skill\` | ✅ Annotated |"
  fi
done)

---
*Generated by \`scripts/guardrail-annotation-audit.sh\`*
EOF

echo "GUARDRAIL Annotation Audit: ${annotated}/${total} annotated"
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "Missing: ${missing[*]}"
  echo "Report: ${REPORT_FILE}"
  exit 1
else
  echo "All moderate+ risk skills annotated ✅"
  echo "Report: ${REPORT_FILE}"
  exit 0
fi
