import logging
import os
import sys

# Configure logging
logging.basicConfig(
  level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("QualityGateMonitor")


def check_quality_gates(log_file_path: str) -> bool:
  """Checks the ingestion logs for "Quality Gates FAILED".
  Returns True if gates passed, False if failed.
  """
  try:
    if not os.path.exists(log_file_path):
      logger.warning(f"Log file not found: {log_file_path}")
      return True  # Assume pass if no log (or handle as error)

    with open(log_file_path) as f:
      content = f.read()
      if "Quality Gates: FAILED" in content:
        logger.error("🚨 ALERT: Quality Gates FAILED for recent ingestion run.")
        return False
      if "Quality Gates: PASSED" in content:
        logger.info("✅ Quality Gates PASSED.")
        return True

    logger.warning("Quality Gate status not found in logs.")
    return True

  except Exception as e:
    logger.exception(f"Error checking logs: {e}")
    return False


def send_alert(message: str) -> None:
  """Simulates sending an alert (e.g., Slack, Email, PagerDuty)."""
  # In a real scenario, use requests.post to a webhook URL


def main() -> None:
  # Path to the log file generated by the ingestion layer
  # In K8s, this might be a shared volume or fetched from Cloud Logging
  LOG_FILE = os.getenv("INGESTION_LOG_FILE", "artifacts/logs/ingestion_latest.log")

  logger.info(f"Checking quality gates in: {LOG_FILE}")

  passed = check_quality_gates(LOG_FILE)

  if not passed:
    send_alert("Quality Gates FAILED. Immediate investigation required.")
    sys.exit(1)

  sys.exit(0)


if __name__ == "__main__":
  main()
