# Copyright (c) 2026 ShadowTag, Inc. All rights reserved.
"""
AM Briefing Generator

Generates morning intelligence briefings from ingested data.
Delivered to services across 4 namespaces.
"""

from typing import Any
from datetime import datetime, timezone
from ..sources.base import IngestionItem
from ..classification.tier_classifier import TierLevel


class AMBriefingGenerator:
    """Generate AM intelligence briefings"""

    def __init__(self, format: str = "markdown"):
        self.format = format

    def generate(self, items: list[IngestionItem], stats: dict[str, Any]) -> str:
        """
        Generate briefing from ingested items.

        Args:
            items: Ingested and classified items
            stats: Ingestion run statistics

        Returns:
            Formatted briefing
        """
        # Filter to Tier 1 and Tier 2 items
        tier_1_items = [i for i in items if i.tier == TierLevel.TIER_1.value]
        tier_2_items = [i for i in items if i.tier == TierLevel.TIER_2.value]

        # Generate markdown briefing
        briefing = []
        briefing.append("# PNKLN Intelligence Briefing")
        briefing.append(f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
        briefing.append("")
        briefing.append("## Summary")
        briefing.append(f"- Total Items: {stats.get('items_ingested', 0)}")
        briefing.append(f"- Tier 1 (High-Value): {len(tier_1_items)}")
        briefing.append(f"- Tier 2 (Medium-Value): {len(tier_2_items)}")
        briefing.append(f"- Sources: {stats.get('unique_sources', 0)}")
        briefing.append("")

        # Top Tier 1 items
        briefing.append("## Priority Intelligence (Tier 1)")
        for item in tier_1_items[:10]:  # Top 10
            briefing.append(f"### {item.title}")
            briefing.append(f"*Source: {item.source} | {item.author}*")
            briefing.append(f"{item.content[:200]}...")
            briefing.append(f"[Read more]({item.url})")
            briefing.append("")

        # Key Tier 2 items
        briefing.append("## Secondary Intelligence (Tier 2)")
        for item in tier_2_items[:5]:  # Top 5
            briefing.append(f"- **{item.title}** ({item.source}) - {item.url}")

        briefing.append("")
        briefing.append("---")
        briefing.append("*Generated by PNKLN Gemini Ingestion Layer*")

        return "\n".join(briefing)

    async def deliver(self, briefing: str, recipients: list[str]) -> bool:
        """
        Deliver briefing to recipients.

        NOTE: In production, implement email/Slack/webhook delivery.

        Args:
            briefing: Generated briefing content
            recipients: List of recipient emails/endpoints

        Returns:
            True if delivered successfully
        """
        # Placeholder - in production, use SendGrid, Slack API, etc.
        print(f"Delivering briefing to {len(recipients)} recipients")
        return True
