apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: hht-squadron-quota
spec:
  owners:
    - name: hht-owner@shadowtag.omega
      kind: User
    - name: flux-hht-sa
      kind: ServiceAccount

  # Namespace propagation
  namespaces:
    template:
      metadata:
        labels:
          toolkit.fluxcd.io/tenant: hht
          app: otel-monkeys
          env: production
          istio-injection: enabled
          colony-mode: PENAL
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/audit: restricted
          pod-security.kubernetes.io/warn: restricted

  # Tenant quota
  resourceQuotas:
    items:
      - hard:
          requests.cpu: '5'
          requests.memory: '10Gi'
          limits.cpu: '10'
          limits.memory: '20Gi'
          pods: '25'
    scope: Tenant

  # Container limits
  limitRanges:
    items:
      - limits:
          - type: Pod
            max:
              cpu: '2'
              memory: '4Gi'
          - type: Container
            default:
              cpu: '500m'
              memory: '512Mi'
            defaultRequest:
              cpu: '200m'
              memory: '256Mi'
