apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penal-monkeys
  namespace: flux-system
  labels:
    config.fluxcd.io/multi-tenant: lockdown
spec:
  chart:
    spec:
      chart: './charts/monkeys7'
      version: '>=1.0.0'
  interval: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  targetNamespace: penal-colony # Tenant ns
  serviceAccountName: hht-flux-sa # Impersonation
  storageNamespace: flux-system # Hub-spoke
  driftDetection:
    mode: Enabled # Deny drift
  valuesFrom:
    - kind: Secret
      name: penal-values
