apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: penal-quota-hard
spec:
  resourceQuotas:
    items:
    - hard:
        limits.cpu: "10"
        limits.memory: "20Gi"
        pods: "25"
    scope: Tenant
  limitRanges:
    items:
    - limits:
      - type: Pod
        max:
          cpu: "2"
          memory: "4Gi"
      - type: Container
        default:
          cpu: "500m"
          memory: "512Mi"
