# Copyright (c) 2026 ShadowTag, Inc. All rights reserved.
import datetime

# Standard US Federal Holidays (Simplified static list for proof-of-concept)
FEDERAL_HOLIDAYS_2026 = [
    datetime.date(2026, 1, 1),  # New Year's Day
    datetime.date(2026, 1, 19),  # MLK Day
    datetime.date(2026, 2, 16),  # Presidents' Day
    datetime.date(2026, 5, 25),  # Memorial Day
    datetime.date(2026, 6, 19),  # Juneteenth
    datetime.date(2026, 7, 3),  # Independence Day (Observed)
    datetime.date(2026, 9, 7),  # Labor Day
    datetime.date(2026, 10, 12),  # Columbus Day
    datetime.date(2026, 11, 11),  # Veterans Day
    datetime.date(2026, 11, 26),  # Thanksgiving
    datetime.date(2026, 12, 25),  # Christmas
]


class FRCPDeadlineCalculator:
    """
    Federal Rules of Civil Procedure (FRCP) Rule 6(a) Time Computation Engine.
    """

    @staticmethod
    def is_weekend(date_obj: datetime.date) -> bool:
        return date_obj.weekday() >= 5  # 5=Sat, 6=Sun

    @staticmethod
    def is_holiday(date_obj: datetime.date) -> bool:
        return date_obj in FEDERAL_HOLIDAYS_2026

    @classmethod
    def compute_deadline(cls, trigger_date: datetime.date, days_added: int) -> datetime.date:
        """
        FRCP 6(a)(1) Rules:
        (A) exclude the day of the event that triggers the period;
        (B) count every day, including intermediate Saturdays, Sundays, and legal holidays; and
        (C) include the last day of the period, but if the last day is a Saturday, Sunday,
            or legal holiday, the period continues to run until the end of the next day that
            is not a Saturday, Sunday, or legal holiday.
        """
        if days_added <= 0:
            raise ValueError("Deadlines must calculate forward in time.")

        # Rule (A) and (B): Add raw days (excluding trigger event day natively via math)
        raw_deadline = trigger_date + datetime.timedelta(days=days_added)

        # Rule (C): Roll forward if landing on Weekend or Holiday
        final_deadline = raw_deadline
        while cls.is_weekend(final_deadline) or cls.is_holiday(final_deadline):
            final_deadline += datetime.timedelta(days=1)

        return final_deadline

    @classmethod
    def evaluate_mcp_extracted_payload(cls, json_payload: dict) -> dict:
        """
        Validates the strict output generated by the Zero-Drift Semantic Extractor.
        Expects: {"trigger_date": "YYYY-MM-DD", "duration_days": 21, "exhibit_id": "doc123"}
        """
        # Army Risk Management Brake: Human-in-the-loop queuing
        if not all(k in json_payload for k in ["trigger_date", "duration_days", "exhibit_id"]):
            return {"status": "error", "message": "Malformed Zero-Drift payload"}

        # Parse logic
        trigger = datetime.date.fromisoformat(json_payload["trigger_date"])
        calculated_date = cls.compute_deadline(trigger, json_payload["duration_days"])

        return {
            "status": "pending_human_verification",  # Mandatory ZT.1 brake
            "exhibit_id": json_payload["exhibit_id"],
            "calculated_deadline": calculated_date.isoformat(),
            "computed_under": "FRCP 6(a)",
        }
