apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cor17-data-pvc
  namespace: cor17
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo
