<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/firestore/admin/v1/backup.proto

namespace GPBMetadata\Google\Firestore\Admin\V1;

class Backup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC7\x07\x0A&google/firestore/admin/v1/backup.proto\x12\x19google.firestore.admin.v1\x1A\x19google/api/resource.proto\x1A\x1Fgoogle/protobuf/timestamp.proto\"\xE0\x04\x0A\x06Backup\x12\x11\x0A\x04name\x18\x01 \x01(\x09B\x03\xE0A\x03\x12;\x0A\x08database\x18\x02 \x01(\x09B)\xE0A\x03\xFAA#\x0A!firestore.googleapis.com/Database\x12\x19\x0A\x0Cdatabase_uid\x18\x07 \x01(\x09B\x03\xE0A\x03\x126\x0A\x0Dsnapshot_time\x18\x03 \x01(\x0B2\x1A.google.protobuf.TimestampB\x03\xE0A\x03\x124\x0A\x0Bexpire_time\x18\x04 \x01(\x0B2\x1A.google.protobuf.TimestampB\x03\xE0A\x03\x12;\x0A\x05stats\x18\x06 \x01(\x0B2'.google.firestore.admin.v1.Backup.StatsB\x03\xE0A\x03\x12;\x0A\x05state\x18\x08 \x01(\x0E2'.google.firestore.admin.v1.Backup.StateB\x03\xE0A\x03\x1AW\x0A\x05Stats\x12\x17\x0A\x0Asize_bytes\x18\x01 \x01(\x03B\x03\xE0A\x03\x12\x1B\x0A\x0Edocument_count\x18\x02 \x01(\x03B\x03\xE0A\x03\x12\x18\x0A\x0Bindex_count\x18\x03 \x01(\x03B\x03\xE0A\x03\"J\x0A\x05State\x12\x15\x0A\x11STATE_UNSPECIFIED\x10\x00\x12\x0C\x0A\x08CREATING\x10\x01\x12\x09\x0A\x05READY\x10\x02\x12\x11\x0A\x0DNOT_AVAILABLE\x10\x03:^\xEAA[\x0A\x1Ffirestore.googleapis.com/Backup\x128projects/{project}/locations/{location}/backups/{backup}B\xDA\x01\x0A\x1Dcom.google.firestore.admin.v1B\x0BBackupProtoP\x01Z9cloud.google.com/go/firestore/apiv1/admin/adminpb;adminpb\xA2\x02\x04GCFS\xAA\x02\x1FGoogle.Cloud.Firestore.Admin.V1\xCA\x02\x1FGoogle\\Cloud\\Firestore\\Admin\\V1\xEA\x02#Google::Cloud::Firestore::Admin::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}
