apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pnkln-production

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - backendconfig.yaml
  - ingress.yaml
  - managedcertificate.yaml

commonLabels:
  app: pnkln
  managed-by: kustomize

images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/pnkln/orchestrator
    newTag: latest
