<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/firestore/admin/v1/user_creds.proto

namespace GPBMetadata\Google\Firestore\Admin\V1;

class UserCreds
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA5\x07\x0A*google/firestore/admin/v1/user_creds.proto\x12\x19google.firestore.admin.v1\x1A\x19google/api/resource.proto\x1A\x1Fgoogle/protobuf/timestamp.proto\"\xB7\x04\x0A\x09UserCreds\x12\x11\x0A\x04name\x18\x01 \x01(\x09B\x03\xE0A\x08\x124\x0A\x0Bcreate_time\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampB\x03\xE0A\x03\x124\x0A\x0Bupdate_time\x18\x03 \x01(\x0B2\x1A.google.protobuf.TimestampB\x03\xE0A\x03\x12>\x0A\x05state\x18\x04 \x01(\x0E2*.google.firestore.admin.v1.UserCreds.StateB\x03\xE0A\x03\x12\x1C\x0A\x0Fsecure_password\x18\x05 \x01(\x09B\x03\xE0A\x03\x12R\x0A\x11resource_identity\x18\x06 \x01(\x0B25.google.firestore.admin.v1.UserCreds.ResourceIdentityH\x00\x1A*\x0A\x10ResourceIdentity\x12\x16\x0A\x09principal\x18\x01 \x01(\x09B\x03\xE0A\x03\"9\x0A\x05State\x12\x15\x0A\x11STATE_UNSPECIFIED\x10\x00\x12\x0B\x0A\x07ENABLED\x10\x01\x12\x0C\x0A\x08DISABLED\x10\x02:}\xEAAz\x0A\"firestore.googleapis.com/UserCreds\x12>projects/{project}/databases/{database}/userCreds/{user_creds}*\x09userCreds2\x09userCredsB\x13\x0A\x11UserCredsIdentityB\xDD\x01\x0A\x1Dcom.google.firestore.admin.v1B\x0EUserCredsProtoP\x01Z9cloud.google.com/go/firestore/apiv1/admin/adminpb;adminpb\xA2\x02\x04GCFS\xAA\x02\x1FGoogle.Cloud.Firestore.Admin.V1\xCA\x02\x1FGoogle\\Cloud\\Firestore\\Admin\\V1\xEA\x02#Google::Cloud::Firestore::Admin::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}
