(() => {}).length;
typeof (() => {});
export default (() => {})();
(() => {})()``;
(() => {})``;
new (function () {})();
() => {};
a = function f() {} || b;
(() => {}) && a;
a + (() => {});
new (function () {})();
