// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export {
  AggregateFunction,
  AliasedAggregate,
  AliasedExpression,
  abs,
  add,
  and,
  array,
  arrayAgg,
  arrayAggDistinct,
  arrayConcat,
  arrayContains,
  arrayContainsAll,
  arrayContainsAny,
  arrayFirst,
  arrayFirstN,
  arrayGet,
  arrayIndexOf,
  arrayIndexOfAll,
  arrayLast,
  arrayLastIndexOf,
  arrayLastN,
  arrayLength,
  arrayMaximum,
  arrayMaximumN,
  arrayMinimum,
  arrayMinimumN,
  arrayReverse,
  arraySum,
  ascending,
  average,
  BooleanExpression,
  byteLength,
  Constant,
  ceil,
  charLength,
  collectionId,
  concat,
  conditional,
  constant,
  cosineDistance,
  count,
  countAll,
  countDistinct,
  countIf,
  currentTimestamp,
  descending,
  divide,
  documentId,
  dotProduct,
  Expression,
  endsWith,
  equal,
  equalAny,
  euclideanDistance,
  exists,
  exp,
  Field,
  FunctionExpression,
  field,
  first,
  floor,
  greaterThan,
  greaterThanOrEqual,
  ifAbsent,
  ifError,
  isAbsent,
  isError,
  isType,
  join,
  last,
  length,
  lessThan,
  lessThanOrEqual,
  like,
  ln,
  log10,
  logicalMaximum,
  logicalMinimum,
  ltrim,
  map,
  mapEntries,
  mapGet,
  mapKeys,
  mapMerge,
  mapRemove,
  mapSet,
  mapValues,
  maximum,
  minimum,
  mod,
  multiply,
  not,
  notEqual,
  notEqualAny,
  Ordering,
  or,
  pow,
  rand,
  regexContains,
  regexFind,
  regexFindAll,
  regexMatch,
  reverse,
  round,
  rtrim,
  split,
  sqrt,
  startsWith,
  stringConcat,
  stringContains,
  stringIndexOf,
  stringRepeat,
  stringReplaceAll,
  stringReplaceOne,
  stringReverse,
  substring,
  subtract,
  sum,
  Type,
  timestampAdd,
  timestampSubtract,
  timestampToUnixMicros,
  timestampToUnixMillis,
  timestampToUnixSeconds,
  timestampTruncate,
  toLower,
  toUpper,
  trim,
  trunc,
  type,
  unixMicrosToTimestamp,
  unixMillisToTimestamp,
  unixSecondsToTimestamp,
  vectorLength,
  xor,
  // TODO(new-expression): Add new expression exports above this line
} from './expression';
export {
  Pipeline,
  PipelineResult,
  PipelineSnapshot,
  PipelineSource,
} from './pipelines';
