# Copyright (c) 2026 ShadowTag, Inc. All rights reserved.

"""Content provenance API endpoints
Implements C2PA content credentials and provenance tracking
"""

from fastapi import APIRouter, HTTPException, status

from app.models.content import (
    C2PAVerificationRequest,
    C2PAVerificationResponse,
    ContentProvenanceRequest,
    ContentProvenanceResponse,
    ManifestAction,
    WatermarkRequest,
    WatermarkResponse,
)
from app.services.content_engine import ContentEngine

router = APIRouter()
content_engine = ContentEngine()


@router.post("/c2pa/verify", response_model=C2PAVerificationResponse)
async def verify_c2pa(request: C2PAVerificationRequest):
    """Verify C2PA content credentials

    Checks:
    - Content authenticity
    - Digital signatures
    - Chain of custody
    - AI generation disclosure
    - Training data usage permissions
    - Tampering detection
    """
    result = await content_engine.verify_c2pa(request)
    return result


@router.post("/provenance/create", response_model=ContentProvenanceResponse)
async def create_provenance(request: ContentProvenanceRequest):
    """Create content provenance record

    Records:
    - Content creation/modification
    - Creator identity
    - Action performed
    - Metadata and context
    - Parent content relationships
    - Optional blockchain anchoring
    """
    result = await content_engine.create_provenance(request)
    return result


@router.get("/provenance/{content_id}", response_model=ContentProvenanceResponse)
async def get_provenance(content_id: str):
    """Get provenance record for content"""
    result = await content_engine.get_provenance(content_id)
    if not result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Provenance record not found for content_id: {content_id}",
        )
    return result


@router.get("/manifest-actions")
async def list_manifest_actions():
    """List supported C2PA manifest actions"""
    return [
        {"action": ManifestAction.CREATED, "description": "Content was originally created"},
        {"action": ManifestAction.EDITED, "description": "Content was edited or modified"},
        {"action": ManifestAction.FILTERED, "description": "Filter or effect was applied"},
        {
            "action": ManifestAction.TRANSCODED,
            "description": "Content was transcoded to different format",
        },
        {"action": ManifestAction.AI_GENERATED, "description": "Content was generated by AI"},
        {"action": ManifestAction.AI_TRAINING, "description": "Content was used for AI training"},
    ]


@router.post("/credentials/attach")
async def attach_credentials(content_id: str, creator_id: str):
    """Attach C2PA credentials to content

    Generates and embeds:
    - Content credentials
    - Digital signature
    - Manifest with assertions
    """
    result = await content_engine.attach_credentials(content_id, creator_id)
    return result


@router.get("/credentials/status/{content_id}")
async def get_credential_status(content_id: str):
    """Get C2PA credential status for content"""
    result = await content_engine.get_credential_status(content_id)
    return result


@router.post("/watermark", response_model=WatermarkResponse)
async def watermark_content(request: WatermarkRequest):
    """Watermark content using ShadowTag v2.0

    Embeds:
    - DCT coefficient watermark (Video)
    - Ultrasonic frequency watermark (Audio)
    - C2PA metadata
    - Blockchain anchor
    """
    result = await content_engine.watermark_content(request)
    return result
