# Copyright (c) 2026 ShadowTag, Inc. All rights reserved.

"""SaaS schema init

Revision ID: d0251b3bb412
Revises:
Create Date: 2026-03-25 15:13:03.215163

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d0251b3bb412"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
