"""Ping

Revision ID: f34235bf6240
Revises: d0251b3bb412
Create Date: 2026-03-25 15:16:08.565638

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "f34235bf6240"
down_revision: str | None = "d0251b3bb412"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
