// This snippet file was generated by processing the source file:
// ./database-next/read-and-write.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

import { getAuth } from 'firebase/auth';
// [START rtdb_social_single_value_read_modular]
import { getDatabase, onValue, ref } from 'firebase/database';

const db = getDatabase();
const auth = getAuth();

const userId = auth.currentUser.uid;
return onValue(ref(db, '/users/' + userId), (snapshot) => {
  const username = (snapshot.val() && snapshot.val().username) || 'Anonymous';
  // ...
}, {
  onlyOnce: true
});
// [END rtdb_social_single_value_read_modular]
